"use client";

import { Fragment, useState, useTransition, useRef } from "react";
import { updateLine, addLine, deleteLine, finalizeBudget, deleteBudget } from "../actions";
import type { BudgetSection, InflationType } from "@/app/generated/prisma/client";

type Line = {
  id: string;
  domain: string | null;
  section: BudgetSection;
  position: number;
  description: string;
  costCategory: InflationType;
  unitType: string;
  isAutoGenerated: boolean;
  salaryHint: string | null;
  notes: string | null;
  y1Units: number; y1UnitCost: number; y1AllocPct: number; y1Total: number;
  y2Units: number; y2UnitCost: number; y2AllocPct: number; y2Total: number;
  y3Units: number; y3UnitCost: number; y3AllocPct: number; y3Total: number;
  y4Units: number; y4UnitCost: number; y4AllocPct: number; y4Total: number;
  y5Units: number; y5UnitCost: number; y5AllocPct: number; y5Total: number;
};

type Budget = {
  id: string;
  name: string;
  domains: string[];
  years: number;
  horizonMonths: number;
  applyInflation: boolean;
  inflationSalaryPct: number;
  inflationOtherPct: number;
  inflationNilPct: number;
  status: "draft" | "final" | "approved";
  lines: Line[];
  domainLabels?: Record<string, string>;
  inputs?: Record<string, number | string | null> | null;
};

type BandKey = 1 | 2 | 3 | 4 | 5;
type Band = { k: BandKey; factor: number; label: string };

/** Year-bands present in this horizon, including pro-rated tail. */
function computeBands(horizonMonths: number): Band[] {
  const fullYears = Math.floor(horizonMonths / 12);
  const tail      = horizonMonths - fullYears * 12;
  const out: Band[] = [];
  for (let k = 1 as BandKey; k <= 5; k = (k + 1) as BandKey) {
    if (k <= fullYears) out.push({ k, factor: 1, label: `Y${k}` });
    else if (k === fullYears + 1 && tail > 0) out.push({ k, factor: tail / 12, label: `Y${k} (${tail}mo)` });
  }
  return out;
}

const yTotalKey = (k: BandKey) => `y${k}Total` as const;
const yUnitsKey = (k: BandKey) => `y${k}Units` as const;
const yCostKey  = (k: BandKey) => `y${k}UnitCost` as const;
const yAllocKey = (k: BandKey) => `y${k}AllocPct` as const;

const DOMAIN_LABELS: Record<string, string> = {
  Children: "Children", Youth: "Youth", Elderly: "Elderly + Kitchen",
  WelfareRights: "Welfare Rights", Creche: "Creche",
};

const SECTION_LABELS: Record<BudgetSection, string> = {
  salary: "1. Salary & Honorarium",
  capex: "2. Fixed Assets / CAPEX",
  travel: "3. Travel",
  programme: "4. Programme Expenses",
  admin_salary: "5a. Admin – Salaries",
  admin_other: "5b. Admin – Other",
  additional: "6. Additional Items",
};

const SECTION_ORDER: BudgetSection[] = ["salary", "capex", "travel", "programme", "admin_salary", "admin_other", "additional"];

const INFLATION_BADGE: Record<InflationType, string> = {
  Salary: "bg-violet-100 text-violet-700",
  Other: "bg-sky-100 text-sky-700",
  Nil: "bg-stone-100 text-stone-500",
};

const fmt = (n: number) => n === 0 ? "–" : `₹${n.toLocaleString("en-IN")}`;

const horizonLabel = (m: number) =>
  m % 12 === 0 ? `${m / 12}-year` : `${m}-month`;

export default function BudgetEditor({ budget }: { budget: Budget }) {
  const domainLabels: Record<string, string> = budget.domainLabels ?? DOMAIN_LABELS;
  const bands = computeBands(budget.horizonMonths ?? budget.years * 12);
  /** Inflation rate per category, as a decimal — gated by the budget's applyInflation flag. */
  const inflationRate: Record<InflationType, number> = budget.applyInflation
    ? { Salary: budget.inflationSalaryPct / 100, Other: budget.inflationOtherPct / 100, Nil: budget.inflationNilPct / 100 }
    : { Salary: 0, Other: 0, Nil: 0 };
  const showAlloc = bands.length > 1;
  const showExtraBands = bands.length > 1;

  const [activeTab, setActiveTab] = useState<string>("master");
  const [lines, setLines] = useState<Line[]>(budget.lines);
  const [editing, setEditing] = useState<string | null>(null);
  const [editVals, setEditVals] = useState<Partial<Line>>({});
  const [pending, startTransition] = useTransition();
  const [addingSection, setAddingSection] = useState<BudgetSection | null>(null);
  const [newDesc, setNewDesc] = useState("");
  const [newCostCat, setNewCostCat] = useState<InflationType>("Other");
  const [newUnitType, setNewUnitType] = useState("Annual");
  const [newUnits, setNewUnits] = useState("");
  const [newUnitCost, setNewUnitCost] = useState("");
  // newDomain controls which per-domain card the manual row joins. "" means
  // cross-cutting (domain=null). Default tracks the active tab so adds from a
  // specific domain tab stay scoped there unless the user picks otherwise.
  const [newDomain, setNewDomain] = useState<string>(
    activeTab !== "master" ? activeTab : (budget.domains[0] ?? "")
  );

  const visibleLines = activeTab === "master"
    ? lines
    : lines.filter(l => l.domain === activeTab || l.domain === null);

  const grouped = SECTION_ORDER.map(sec => ({
    section: sec,
    lines: visibleLines.filter(l => l.section === sec),
  })).filter(g => g.lines.length > 0 || ["admin_salary", "admin_other", "additional"].includes(g.section));

  const sectionTotal = (sec: BudgetSection, k: BandKey) =>
    lines.filter(l => l.section === sec).reduce((s, l) => s + l[yTotalKey(k)], 0);

  const grandTotal = (k: BandKey) =>
    visibleLines.reduce((s, l) => s + l[yTotalKey(k)], 0);

  const horizonTotal = () =>
    bands.reduce((s, b) => s + grandTotal(b.k), 0);

  const grandTotalLabel = activeTab === "master" ? "All domains" : (domainLabels[activeTab] ?? activeTab);

  const hasInputs = (() => {
    if (!budget.inputs) return false;
    const { extraInputs, ...top } = budget.inputs as Record<string, unknown>;
    const isCountEntry = ([k, v]: [string, unknown]) => k.startsWith("n") && typeof v === "number" && v > 0;
    return Object.entries(top).some(isCountEntry) ||
      (extraInputs != null && typeof extraInputs === "object" && Object.entries(extraInputs as Record<string, unknown>).some(isCountEntry));
  })();

  const startEdit = (l: Line) => {
    setEditing(l.id);
    setEditVals({
      description: l.description,
      domain: l.domain,
      y1Units: l.y1Units, y1UnitCost: l.y1UnitCost, y1AllocPct: l.y1AllocPct,
      y2Units: l.y2Units, y2UnitCost: l.y2UnitCost, y2AllocPct: l.y2AllocPct,
      y3Units: l.y3Units, y3UnitCost: l.y3UnitCost, y3AllocPct: l.y3AllocPct,
      y4Units: l.y4Units, y4UnitCost: l.y4UnitCost, y4AllocPct: l.y4AllocPct,
      y5Units: l.y5Units, y5UnitCost: l.y5UnitCost, y5AllocPct: l.y5AllocPct,
    });
  };

  const saveEdit = (lineId: string) => {
    const updated = { ...editVals };
    // Recompute totals locally for immediate feedback
    const tot = (u?: number, c?: number, a?: number) => Math.round((u ?? 0) * (c ?? 0) * (a ?? 1));
    const totals: Partial<Line> = {
      y1Total: tot(updated.y1Units, updated.y1UnitCost, updated.y1AllocPct),
      y2Total: tot(updated.y2Units, updated.y2UnitCost, updated.y2AllocPct),
      y3Total: tot(updated.y3Units, updated.y3UnitCost, updated.y3AllocPct),
      y4Total: tot(updated.y4Units, updated.y4UnitCost, updated.y4AllocPct),
      y5Total: tot(updated.y5Units, updated.y5UnitCost, updated.y5AllocPct),
    };
    setLines(prev => prev.map(l => l.id === lineId ? { ...l, ...updated, ...totals } : l));
    setEditing(null);
    startTransition(() => updateLine(lineId, updated));
  };

  const handleDelete = (lineId: string) => {
    setLines(prev => prev.filter(l => l.id !== lineId));
    startTransition(() => deleteLine(lineId));
  };

  const handleAddLine = (section: BudgetSection) => {
    if (!newDesc.trim()) return;
    // Empty string means cross-cutting (domain=null in the DB) so passes
    // through as undefined to the server action.
    const domain = newDomain || undefined;
    startTransition(async () => {
      const line = await addLine(budget.id, {
        section,
        description: newDesc.trim(),
        costCategory: newCostCat,
        unitType: newUnitType,
        domain,
        y1Units: parseFloat(newUnits) || 0,
        y1UnitCost: parseFloat(newUnitCost) || 0,
      });
      setLines(prev => [...prev, line as unknown as Line]);
      setAddingSection(null);
      setNewDesc(""); setNewUnits(""); setNewUnitCost("");
    });
  };

  return (
    <div>
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-start gap-3 mb-6">
        <div className="flex-1 min-w-0">
          <div className="flex flex-wrap items-center gap-2">
            <h1 className="text-xl font-semibold text-stone-900">{budget.name}</h1>
            <span className={`text-xs px-2 py-0.5 rounded-full ${budget.status === "approved" ? "bg-emerald-100 text-emerald-700" : budget.status === "final" ? "bg-green-100 text-green-700" : "bg-amber-100 text-amber-700"}`}>
              {budget.status === "approved" ? "Approved" : budget.status === "final" ? "Finalized" : "Draft"}
            </span>
            <span className="text-xs text-stone-400">
              {horizonLabel(budget.horizonMonths ?? budget.years * 12)}
              {!budget.applyInflation && <span className="ml-1 text-stone-300">· flat</span>}
            </span>
          </div>
          <div className="mt-1 flex flex-wrap gap-1">
            {budget.domains.map(d => <span key={d} className="text-xs bg-stone-100 text-stone-600 px-2 py-0.5 rounded">{domainLabels[d] ?? d}</span>)}
          </div>
        </div>
        <div className="flex flex-wrap gap-2">
          {budget.status === "approved" && (
            <a href={`/budget/${budget.id}/reports`}
              className="text-sm bg-emerald-600 text-white px-3 py-1.5 rounded-lg hover:bg-emerald-700">
              Reports
            </a>
          )}
          <a href={`/budget/${budget.id}/analysis`}
            className="text-sm border border-stone-300 px-3 py-1.5 rounded-lg hover:bg-stone-50 text-stone-700">
            Analysis
          </a>
          <button
            type="button"
            onClick={async () => {
              try {
                const res = await fetch(`/budget/${budget.id}/export`);
                if (!res.ok) { alert(`Export failed (${res.status})`); return; }
                const blob = await res.blob();
                const cd = res.headers.get("Content-Disposition") ?? "";
                const m = cd.match(/filename="?([^";]+)"?/);
                const url = URL.createObjectURL(blob);
                const a = document.createElement("a");
                a.href = url;
                a.download = m?.[1] ?? `${budget.name}_budget.xlsx`;
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
                setTimeout(() => URL.revokeObjectURL(url), 1000);
              } catch {
                alert("Export failed. Please try again.");
              }
            }}
            className="text-sm border border-stone-300 px-3 py-1.5 rounded-lg hover:bg-stone-50 text-stone-700">
            Export
          </button>
          {budget.status === "draft" && (
            <button
              onClick={() => startTransition(() => finalizeBudget(budget.id))}
              disabled={pending}
              className="text-sm bg-sky-600 text-white px-3 py-1.5 rounded-lg hover:bg-sky-700 disabled:opacity-60">
              Finalize
            </button>
          )}
        </div>
      </div>

      {/* Grand total bar */}
      {hasInputs && (
        <div className="bg-sky-50 border border-sky-200 rounded-xl px-5 py-4 mb-6 flex flex-wrap gap-6 items-start">
          <div className="self-center text-xs font-semibold text-sky-700 uppercase tracking-wide min-w-[100px]">
            {grandTotalLabel}
          </div>
          {bands.map(b => (
            <TotalCell key={b.k}
              label={`${b.label} Total`}
              value={grandTotal(b.k)}
              big={b.k === 1}
            />
          ))}
          {bands.length > 1 && (
            <TotalCell label={`${horizonLabel(budget.horizonMonths ?? budget.years * 12)} Total`}
              value={horizonTotal()} big />
          )}
        </div>
      )}

      {/* Domain tabs */}
      <div className="flex gap-1 mb-4 overflow-x-auto pb-1">
        {(["master", ...budget.domains] as const).map(tab => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`text-sm px-4 py-1.5 rounded-lg whitespace-nowrap transition-all ${
              activeTab === tab ? "bg-sky-600 text-white" : "text-stone-600 hover:bg-stone-100"
            }`}
          >
            {tab === "master" ? "Master Summary" : (domainLabels[tab] ?? tab)}
          </button>
        ))}
      </div>

      {/* Line item tables */}
      <div className="space-y-6">
        {grouped.map(({ section, lines: sLines }) => (
          <div key={section} className="bg-white border border-stone-200 rounded-xl overflow-hidden">
            <div className="flex items-center justify-between px-4 py-2.5 bg-stone-50 border-b border-stone-200">
              <span className="text-sm font-semibold text-stone-700">{SECTION_LABELS[section]}</span>
              <span className="text-sm text-stone-500">{fmt(sLines.reduce((s, l) => s + l.y1Total, 0))}</span>
            </div>

            <div className="overflow-x-auto">
            <table className="w-full min-w-[520px] text-sm">
              <thead>
                <tr className="border-b border-stone-100 text-xs text-stone-400">
                  <th className="text-left px-4 py-2 w-8">#</th>
                  <th className="text-left px-2 py-2">Description</th>
                  <th className="text-right px-2 py-2 w-20">Units</th>
                  <th className="text-right px-2 py-2 w-28">Unit Cost</th>
                  {showAlloc && <th className="text-right px-2 py-2 w-16">Alloc%</th>}
                  {bands.map(b => (
                    <th key={b.k} className="text-right px-2 py-2 w-28">{b.label}</th>
                  ))}
                  <th className="w-16 px-2 py-2"></th>
                </tr>
              </thead>
              <tbody>
                {sLines.map((l, i) => (
                  editing === l.id
                    ? <EditRow key={l.id} line={l} vals={editVals} setVals={setEditVals}
                        bands={bands} showAlloc={showAlloc}
                        domains={budget.domains} domainLabels={domainLabels}
                        onSave={() => saveEdit(l.id)} onCancel={() => setEditing(null)} />
                    : <ViewRow key={l.id} line={l} i={i + 1} bands={bands} showAlloc={showAlloc}
                        onEdit={() => startEdit(l)} onDelete={() => handleDelete(l.id)} />
                ))}
              </tbody>
              <tfoot>
                <tr className="border-t border-stone-200 bg-stone-50 font-medium text-stone-700">
                  <td className="px-4 py-2" colSpan={4 + (showAlloc ? 1 : 0)}>Section total</td>
                  {bands.map(b => (
                    <td key={b.k} className="text-right px-2 py-2">
                      {fmt(sLines.reduce((s, l) => s + l[yTotalKey(b.k)], 0))}
                    </td>
                  ))}
                  <td />
                </tr>
              </tfoot>
            </table>
            </div>

            {/* Add row button */}
            {addingSection === section ? (
              <div className="px-4 py-3 border-t border-stone-100 space-y-2">
                <div className="flex flex-wrap gap-2 items-end">
                  <input
                    autoFocus
                    value={newDesc}
                    onChange={e => setNewDesc(e.target.value)}
                    placeholder="Description"
                    className="flex-1 min-w-48 border border-stone-300 rounded px-2 py-1 text-sm focus:outline-none focus:ring-1 focus:ring-sky-500"
                  />
                  <select value={newCostCat} onChange={e => setNewCostCat(e.target.value as InflationType)}
                    className="border border-stone-300 rounded px-2 py-1 text-xs focus:outline-none">
                    <option value="Salary">Salary inflation (10%)</option>
                    <option value="Other">Other inflation (5%)</option>
                    <option value="Nil">No inflation</option>
                  </select>
                  <select value={newDomain} onChange={e => setNewDomain(e.target.value)}
                    className="border border-stone-300 rounded px-2 py-1 text-xs focus:outline-none"
                    title="Which per-domain card this row belongs to. Cross-cutting = shared admin / travel / shared.">
                    <option value="">Cross-cutting</option>
                    {budget.domains.map(d => (
                      <option key={d} value={d}>{domainLabels[d] ?? d}</option>
                    ))}
                  </select>
                  <input value={newUnitType} onChange={e => setNewUnitType(e.target.value)}
                    placeholder="Unit label" className="w-28 border border-stone-300 rounded px-2 py-1 text-xs focus:outline-none" />
                </div>
                <div className="flex flex-wrap gap-2 items-end">
                  <input type="number" value={newUnits} onChange={e => setNewUnits(e.target.value)}
                    placeholder="Units (Y1)" className="w-28 border border-stone-300 rounded px-2 py-1 text-sm focus:outline-none" />
                  <input type="number" value={newUnitCost} onChange={e => setNewUnitCost(e.target.value)}
                    placeholder="Unit cost ₹ (Y1)" className="w-36 border border-stone-300 rounded px-2 py-1 text-sm focus:outline-none" />
                  {newUnits && newUnitCost && (
                    <span className="text-xs text-stone-500">
                      Y1: ₹{Math.round((parseFloat(newUnits)||0)*(parseFloat(newUnitCost)||0)*bands[0].factor).toLocaleString("en-IN")}
                      {showExtraBands && (() => {
                        const rate = inflationRate[newCostCat];
                        const u = parseFloat(newUnits) || 0;
                        const c = parseFloat(newUnitCost) || 0;
                        return bands.slice(1).map(b => {
                          const yc = c * Math.pow(1 + rate, b.k - 1);
                          const yt = Math.round(u * yc * b.factor);
                          return <Fragment key={b.k}> · {b.label}: ₹{yt.toLocaleString("en-IN")}</Fragment>;
                        });
                      })()}
                    </span>
                  )}
                  <div className="flex gap-2 ml-auto">
                    <button onClick={() => handleAddLine(section)} disabled={!newDesc.trim() || pending}
                      className="text-xs bg-sky-600 text-white px-3 py-1.5 rounded hover:bg-sky-700 disabled:opacity-50">Add</button>
                    <button onClick={() => setAddingSection(null)} className="text-xs text-stone-400 hover:text-stone-700">Cancel</button>
                  </div>
                </div>
              </div>
            ) : (
              <button
                onClick={() => {
                  setAddingSection(section);
                  // Refresh the default each time the form opens so it tracks
                  // whichever tab the user is currently focused on.
                  setNewDomain(activeTab !== "master" ? activeTab : (budget.domains[0] ?? ""));
                }}
                className="w-full text-left px-4 py-2 text-xs text-stone-400 hover:text-sky-600 hover:bg-sky-50 border-t border-stone-100 transition-colors">
                + Add line
              </button>
            )}
          </div>
        ))}
      </div>

      {/* Grand total footer */}
      {hasInputs && (
        <div className="mt-6 bg-stone-900 text-white rounded-xl px-5 py-4 flex flex-wrap gap-6 items-start">
          <div className="self-center">
            <div className="text-xs text-stone-400 uppercase tracking-wide">Grand Total</div>
            <div className="text-sm font-semibold text-white">{grandTotalLabel}</div>
          </div>
          {bands.map(b => (
            <TotalCell key={b.k} label={b.label} value={grandTotal(b.k)} big={b.k === 1} white />
          ))}
          {bands.length > 1 && (
            <TotalCell label={`${horizonLabel(budget.horizonMonths ?? budget.years * 12)} Total`}
              value={horizonTotal()} big white />
          )}
        </div>
      )}
    </div>
  );
}

function TotalCell({ label, value, big, white }: { label: string; value: number; big?: boolean; white?: boolean }) {
  return (
    <div>
      <div className={`text-xs ${white ? "text-stone-400" : "text-stone-500"}`}>{label}</div>
      <div className={`font-semibold ${big ? "text-xl" : "text-base"} ${white ? "text-white" : "text-stone-900"}`}>
        ₹{(value / 100000).toFixed(2)}L
      </div>
    </div>
  );
}

function ViewRow({ line, i, bands, showAlloc, onEdit, onDelete }: {
  line: Line; i: number; bands: Band[]; showAlloc: boolean;
  onEdit: () => void; onDelete: () => void;
}) {
  const [showDelete, setShowDelete] = useState(false);
  return (
    <tr className="border-b border-stone-50 hover:bg-stone-50 group">
      <td className="px-4 py-2 text-stone-400 text-xs">{i}</td>
      <td className="px-2 py-2">
        <div className="flex items-center gap-2">
          <span className="text-stone-800">{line.description}</span>
          <span className={`text-xs px-1.5 py-0.5 rounded ${INFLATION_BADGE[line.costCategory]}`}>{line.costCategory}</span>
          {line.salaryHint && line.y1UnitCost === 0 && (
            <span className="text-xs text-amber-600 italic">hint: {line.salaryHint}</span>
          )}
        </div>
        {line.notes && <div className="text-xs text-stone-400 mt-0.5">{line.notes}</div>}
      </td>
      <td className="text-right px-2 py-2 text-stone-500 text-xs">{line.y1Units > 0 ? line.y1Units : "–"}</td>
      <td className="text-right px-2 py-2 text-stone-500 text-xs">{line.y1UnitCost > 0 ? `₹${line.y1UnitCost.toLocaleString("en-IN")}` : "–"}</td>
      {showAlloc && <td className="text-right px-2 py-2 text-stone-400 text-xs">{line.y1AllocPct < 1 ? `${(line.y1AllocPct * 100).toFixed(0)}%` : "100%"}</td>}
      {bands.map(b => {
        const total = line[yTotalKey(b.k)];
        const isFirst = b.k === 1;
        return (
          <td key={b.k}
            className={`text-right px-2 py-2 ${isFirst ? `font-medium ${total === 0 ? "text-amber-500" : "text-stone-900"}` : "text-stone-600"}`}>
            {fmt(total)}
          </td>
        );
      })}
      <td className="px-2 py-2">
        <div className="flex gap-1 opacity-100 sm:opacity-0 sm:group-hover:opacity-100 transition-opacity">
          <button onClick={onEdit} className="text-xs text-sky-600 hover:text-sky-800">Edit</button>
          {!line.isAutoGenerated && (
            showDelete
              ? <button onClick={onDelete} className="text-xs text-red-600 hover:text-red-800">Confirm</button>
              : <button onClick={() => setShowDelete(true)} className="text-xs text-stone-400 hover:text-red-500">Del</button>
          )}
        </div>
      </td>
    </tr>
  );
}

function EditRow({ line, vals, setVals, bands, showAlloc, domains, domainLabels, onSave, onCancel }: {
  line: Line; vals: Partial<Line>; setVals: (v: Partial<Line>) => void;
  bands: Band[]; showAlloc: boolean;
  domains: string[]; domainLabels: Record<string, string>;
  onSave: () => void; onCancel: () => void;
}) {
  // Edit row keeps inflation-aware auto-fill but uses zero rate when applyInflation
  // is off (band.factor stays 1 in those cases). The parent already gates extra
  // bands on showAlloc / bands.length.
  const setY1Units = (v: number) => {
    const next: Partial<Line> = { ...vals, y1Units: v };
    for (const b of bands) {
      if (b.k === 1) continue;
      next[yUnitsKey(b.k)] = v * b.factor;
    }
    setVals(next);
  };

  const setY1UnitCost = (v: number) => {
    const next: Partial<Line> = { ...vals, y1UnitCost: v };
    // Re-compute Y2..Y5 from existing cost ratio. Use a conservative inflation
    // pass: same rate per year as the line's current Y1→Y2 step.
    const ratio = line.y1UnitCost > 0 ? line.y2UnitCost / line.y1UnitCost : 1;
    let cur = v;
    for (const b of bands) {
      if (b.k === 1) continue;
      cur = Math.round(cur * ratio);
      next[yCostKey(b.k)] = cur;
    }
    setVals(next);
  };

  const preview = (k: BandKey) =>
    Math.round((vals[yUnitsKey(k)] ?? 0) * (vals[yCostKey(k)] ?? 0) * (vals[yAllocKey(k)] ?? 1));

  return (
    <tr className="border-b border-sky-100 bg-sky-50">
      <td className="px-4 py-2 text-stone-400 text-xs">✏</td>
      <td className="px-2 py-1.5">
        <input
          value={vals.description ?? ""}
          onChange={e => setVals({ ...vals, description: e.target.value })}
          className="w-full border border-sky-300 rounded px-2 py-1 text-sm focus:outline-none focus:ring-1 focus:ring-sky-500"
        />
        <div className="flex items-center gap-2 mt-1">
          <span className="text-[10px] uppercase tracking-widest text-stone-400">Domain</span>
          <select value={vals.domain ?? ""}
            onChange={e => setVals({ ...vals, domain: e.target.value === "" ? null : e.target.value })}
            className="border border-sky-200 rounded px-1.5 py-0.5 text-xs focus:outline-none focus:ring-1 focus:ring-sky-500 bg-white">
            <option value="">Cross-cutting</option>
            {domains.map(d => (
              <option key={d} value={d}>{domainLabels[d] ?? d}</option>
            ))}
          </select>
        </div>
        {line.salaryHint && <p className="text-xs text-amber-600 mt-0.5">Suggested: {line.salaryHint}</p>}
      </td>
      <td className="px-2 py-1.5">
        <input type="number" value={vals.y1Units || ""} placeholder="Units"
          onChange={e => setY1Units(parseFloat(e.target.value) || 0)}
          className="w-full border border-sky-300 rounded px-2 py-1 text-sm text-right focus:outline-none" />
      </td>
      <td className="px-2 py-1.5">
        <input type="number" value={vals.y1UnitCost || ""} placeholder="Unit cost"
          onChange={e => setY1UnitCost(parseFloat(e.target.value) || 0)}
          className="w-full border border-sky-300 rounded px-2 py-1 text-sm text-right focus:outline-none" />
      </td>
      {showAlloc && (
        <td className="px-2 py-1.5">
          <input type="number" value={(vals.y1AllocPct ?? 1) * 100 || ""} step="0.1"
            onChange={e => setVals({ ...vals, y1AllocPct: (parseFloat(e.target.value) || 100) / 100 })}
            className="w-full border border-sky-300 rounded px-2 py-1 text-xs text-right focus:outline-none" />
        </td>
      )}
      {bands.map(b => b.k === 1 ? (
        <td key={b.k} className="text-right px-2 py-1.5 font-medium text-sky-700">{fmt(preview(1))}</td>
      ) : (
        <td key={b.k} className="px-2 py-1.5">
          <input type="number" value={vals[yCostKey(b.k)] || ""} placeholder={`${b.label} cost`}
            onChange={e => setVals({ ...vals, [yCostKey(b.k)]: parseFloat(e.target.value) || 0 })}
            className="w-full border border-sky-200 rounded px-1.5 py-0.5 text-xs text-right focus:outline-none" />
          <div className="text-right text-xs text-sky-600 mt-0.5">{fmt(preview(b.k))}</div>
        </td>
      ))}
      <td className="px-2 py-1.5">
        <div className="flex gap-1">
          <button onClick={onSave} className="text-xs bg-sky-600 text-white px-2 py-0.5 rounded hover:bg-sky-700">Save</button>
          <button onClick={onCancel} className="text-xs text-stone-400 hover:text-stone-700">×</button>
        </div>
      </td>
    </tr>
  );
}
