"use client";

import { Fragment, useState, useTransition, useRef } from "react";
import { updateLine, addLine, deleteLine, finalizeBudget, deleteBudget, updateBudgetGrantPartner, saveBudgetLineComponents, getBudgetLineHistory } from "../actions";
import type { BudgetSection, BudgetLineCadence, InflationType } from "@/app/generated/prisma/client";

type WorkingComp = { label: string; spec: string | null; qty: number; unitCost: number };
type LineWorking = { components: WorkingComp[]; derivation: string | null; isOwn: boolean };
type LineHistRow = { id: string; oldCost: number | null; newCost: number | null; source: string | null; changedBy: string | null; changedAt: string };

type Line = {
  id: string;
  deliveryPartnerId: string | null;
  domain: string | null;
  section: BudgetSection;
  position: number;
  description: string;
  costCategory: InflationType;
  unitType: string;
  isAutoGenerated: boolean;
  salaryHint: string | null;
  notes: string | null;
  cadence: BudgetLineCadence;
  plannedMonths: number[];
  y1Units: number; y1UnitCost: number; y1AllocPct: number; y1Total: number;
  y2Units: number; y2UnitCost: number; y2AllocPct: number; y2Total: number;
  y3Units: number; y3UnitCost: number; y3AllocPct: number; y3Total: number;
  y4Units: number; y4UnitCost: number; y4AllocPct: number; y4Total: number;
  y5Units: number; y5UnitCost: number; y5AllocPct: number; y5Total: number;
};

type Budget = {
  id: string;
  name: string;
  domains: string[];
  years: number;
  horizonMonths: number;
  partialPosition?: "start" | "end";
  applyInflation: boolean;
  inflationSalaryPct: number;
  inflationOtherPct: number;
  inflationNilPct: number;
  status: "draft" | "final" | "approved";
  importedAt?: string | null;
  grantPartnerId?: string | null;
  grantPartners?: { id: string; name: string }[];
  isMultiPartner?: boolean;
  deliveryPartners?: { id: string; name: string; sortOrder: number; sharedPct: number }[];
  lines: Line[];
  domainLabels?: Record<string, string>;
  inputs?: Record<string, number | string | null> | null;
  workingByLineId?: Record<string, LineWorking>;
};

type BandKey = 1 | 2 | 3 | 4 | 5;
type Band = { k: BandKey; factor: number; label: string };

/** Year-bands present in this horizon, including the pro-rated stub. The stub
 *  is the final band ("end") or Year 1 ("start"). */
function computeBands(horizonMonths: number, partialPosition: "start" | "end" = "end"): Band[] {
  const fullYears = Math.floor(horizonMonths / 12);
  const tail      = horizonMonths - fullYears * 12;
  const out: Band[] = [];
  const totalBands = tail > 0 ? fullYears + 1 : fullYears;
  for (let k = 1 as BandKey; k <= 5; k = (k + 1) as BandKey) {
    if (k > totalBands) continue;
    if (tail > 0 && partialPosition === "start" && k === 1) {
      out.push({ k, factor: tail / 12, label: `Y1 (${tail}mo)` });
    } else if (tail > 0 && partialPosition === "end" && k === fullYears + 1) {
      out.push({ k, factor: tail / 12, label: `Y${k} (${tail}mo)` });
    } else {
      out.push({ k, factor: 1, label: `Y${k}` });
    }
  }
  return out;
}

const yTotalKey = (k: BandKey) => `y${k}Total` as const;
const yUnitsKey = (k: BandKey) => `y${k}Units` as const;
const yCostKey  = (k: BandKey) => `y${k}UnitCost` as const;
const yAllocKey = (k: BandKey) => `y${k}AllocPct` as const;

const DOMAIN_LABELS: Record<string, string> = {
  Children: "Children", Youth: "Youth", Elderly: "Elderly + Kitchen",
  WelfareRights: "Welfare Rights", Creche: "Creche",
};

const SECTION_LABELS: Record<BudgetSection, string> = {
  salary: "1. Salary & Honorarium",
  capex: "2. Fixed Assets / CAPEX",
  travel: "3. Travel",
  programme: "4. Programme Expenses",
  admin_salary: "5a. Admin – Salaries",
  admin_other: "5b. Admin – Other",
  additional: "6. Additional Items",
};

const SECTION_ORDER: BudgetSection[] = ["salary", "capex", "travel", "programme", "admin_salary", "admin_other", "additional"];

const INFLATION_BADGE: Record<InflationType, string> = {
  Salary: "bg-violet-100 text-violet-700",
  Other: "bg-sky-100 text-sky-700",
  Nil: "bg-stone-100 text-stone-500",
};

const fmt = (n: number) => n === 0 ? "–" : `₹${n.toLocaleString("en-IN")}`;

const CADENCE_LABELS: Record<BudgetLineCadence, string> = {
  monthly: "Monthly",
  one_time: "One-time",
  seasonal: "Seasonal",
};

/** Format a planned-months array as a short chip body: "M1" / "M3, M9". */
const formatPlannedMonths = (months: number[]) =>
  months.length ? months.map(m => `M${m}`).join(", ") : "—";

/** Lightweight cadence picker — used in both the add-line form and EditRow. */
function CadencePicker({
  cadence, plannedMonths, onChange,
}: {
  cadence: BudgetLineCadence;
  plannedMonths: number[];
  onChange: (next: { cadence: BudgetLineCadence; plannedMonths: number[] }) => void;
}) {
  const toggleMonth = (m: number) => {
    const next = plannedMonths.includes(m)
      ? plannedMonths.filter(x => x !== m)
      : [...plannedMonths, m].sort((a, b) => a - b);
    onChange({ cadence, plannedMonths: next });
  };
  return (
    <div className="flex flex-wrap items-center gap-1.5">
      <select
        value={cadence}
        onChange={e => {
          const next = e.target.value as BudgetLineCadence;
          // Sensible defaults: monthly clears months, one_time seeds [1], seasonal keeps existing if ≥ 2 else empty.
          const months =
            next === "monthly" ? [] :
            next === "one_time" ? (plannedMonths.length === 1 ? plannedMonths : [1]) :
            (plannedMonths.length >= 2 ? plannedMonths : []);
          onChange({ cadence: next, plannedMonths: months });
        }}
        className="border border-stone-300 rounded px-1.5 py-0.5 text-xs bg-white focus:outline-none focus:ring-1 focus:ring-sky-500"
      >
        <option value="monthly">Monthly</option>
        <option value="one_time">One-time</option>
        <option value="seasonal">Seasonal</option>
      </select>
      {cadence === "one_time" && (
        <label className="text-xs text-stone-500 flex items-center gap-1">
          Month
          <input
            type="number" min={1} max={12}
            value={plannedMonths[0] ?? 1}
            onChange={e => {
              const m = Math.min(12, Math.max(1, parseInt(e.target.value) || 1));
              onChange({ cadence, plannedMonths: [m] });
            }}
            className="w-12 border border-stone-300 rounded px-1.5 py-0.5 text-xs text-right focus:outline-none focus:ring-1 focus:ring-sky-500"
          />
        </label>
      )}
      {cadence === "seasonal" && (
        <div className="flex flex-wrap gap-1">
          {Array.from({ length: 12 }, (_, i) => i + 1).map(m => (
            <button
              key={m}
              type="button"
              onClick={() => toggleMonth(m)}
              className={`text-[10px] px-1.5 py-0.5 rounded border ${
                plannedMonths.includes(m)
                  ? "bg-sky-600 text-white border-sky-600"
                  : "bg-white text-stone-500 border-stone-300 hover:bg-stone-50"
              }`}
            >M{m}</button>
          ))}
          {plannedMonths.length < 2 && (
            <span className="text-[10px] text-amber-600 self-center ml-1">pick ≥ 2 months</span>
          )}
        </div>
      )}
    </div>
  );
}

const horizonLabel = (m: number) =>
  m % 12 === 0 ? `${m / 12}-year` : `${m}-month`;

export default function BudgetEditor({ budget }: { budget: Budget }) {
  const domainLabels: Record<string, string> = budget.domainLabels ?? DOMAIN_LABELS;
  const bands = computeBands(budget.horizonMonths ?? budget.years * 12, budget.partialPosition ?? "end");
  /** Inflation rate per category, as a decimal — gated by the budget's applyInflation flag. */
  const inflationRate: Record<InflationType, number> = budget.applyInflation
    ? { Salary: budget.inflationSalaryPct / 100, Other: budget.inflationOtherPct / 100, Nil: budget.inflationNilPct / 100 }
    : { Salary: 0, Other: 0, Nil: 0 };
  const showAlloc = bands.length > 1;
  const showExtraBands = bands.length > 1;

  const [activeTab, setActiveTab] = useState<string>("master");
  const partners = budget.deliveryPartners ?? [];
  const isMultiPartner = !!budget.isMultiPartner && partners.length > 0;
  // Which delivery partner is in view: "master" = shared lines + roll-up, else a partner id.
  const [activePartner, setActivePartner] = useState<string>("master");
  const [lines, setLines] = useState<Line[]>(budget.lines);
  const [editing, setEditing] = useState<string | null>(null);
  const [editVals, setEditVals] = useState<Partial<Line>>({});
  const [pending, startTransition] = useTransition();

  // ── Per-line working (component breakup + history) ──────────────────────────
  const [working, setWorking] = useState<Record<string, LineWorking>>(budget.workingByLineId ?? {});
  const [workLineId, setWorkLineId] = useState<string | null>(null);
  const [histByLine, setHistByLine] = useState<Record<string, LineHistRow[]>>({});
  const [histLoading, setHistLoading] = useState(false);
  type WRow = { label: string; spec: string; qty: string; unitCost: string };
  const [wEditing, setWEditing] = useState(false);
  const [wRows, setWRows] = useState<WRow[]>([]);
  const [wDeriv, setWDeriv] = useState("");
  const wRollup = Math.round(wRows.reduce((s, r) => s + (parseFloat(r.qty) || 0) * (parseFloat(r.unitCost) || 0), 0));

  function toggleWorking(lineId: string) {
    if (workLineId === lineId) { setWorkLineId(null); setWEditing(false); return; }
    setWorkLineId(lineId); setWEditing(false);
    if (!histByLine[lineId]) {
      setHistLoading(true);
      getBudgetLineHistory(lineId).then(rows => setHistByLine(p => ({ ...p, [lineId]: rows }))).finally(() => setHistLoading(false));
    }
  }
  function startWEdit(lineId: string) {
    const w = working[lineId];
    setWRows((w?.components ?? []).map(c => ({ label: c.label, spec: c.spec ?? "", qty: String(c.qty), unitCost: String(c.unitCost) })));
    setWDeriv(w?.derivation ?? "");
    setWEditing(true);
  }
  const addWRow = () => setWRows(p => [...p, { label: "", spec: "", qty: "1", unitCost: "" }]);
  const updateWRow = (idx: number, k: keyof WRow, v: string) => setWRows(p => p.map((r, i) => i === idx ? { ...r, [k]: v } : r));
  const removeWRow = (idx: number) => setWRows(p => p.filter((_, i) => i !== idx));

  function saveWorking(line: Line) {
    const comps = wRows.map(r => ({ label: r.label, spec: r.spec || null, qty: parseFloat(r.qty) || 0, unitCost: parseFloat(r.unitCost) || 0 })).filter(r => r.label.trim());
    const rollup = Math.round(comps.reduce((s, r) => s + r.qty * r.unitCost, 0));
    startTransition(async () => {
      await saveBudgetLineComponents(line.id, comps, wDeriv.trim() || null);
      // Optimistically reflect the new base cost + scaled years locally.
      const ratio = line.y1UnitCost > 0 && comps.length > 0 ? rollup / line.y1UnitCost : 1;
      setLines(prev => prev.map(l => {
        if (l.id !== line.id || comps.length === 0) return l;
        const sc = (c: number) => (l.y1UnitCost > 0 ? Math.round(c * ratio) : rollup);
        const y1 = rollup, y2 = sc(l.y2UnitCost), y3 = sc(l.y3UnitCost), y4 = sc(l.y4UnitCost), y5 = sc(l.y5UnitCost);
        const t = (u: number, c: number, a: number) => Math.round(u * c * a);
        return { ...l, y1UnitCost: y1, y1Total: t(l.y1Units, y1, l.y1AllocPct), y2UnitCost: y2, y2Total: t(l.y2Units, y2, l.y2AllocPct), y3UnitCost: y3, y3Total: t(l.y3Units, y3, l.y3AllocPct), y4UnitCost: y4, y4Total: t(l.y4Units, y4, l.y4AllocPct), y5UnitCost: y5, y5Total: t(l.y5Units, y5, l.y5AllocPct) };
      }));
      setWorking(p => ({ ...p, [line.id]: { components: comps.map(c => ({ label: c.label, spec: c.spec, qty: c.qty, unitCost: c.unitCost })), derivation: wDeriv.trim() || null, isOwn: true } }));
      setHistByLine(p => ({ ...p, [line.id]: [] })); // force reload next open
      setWEditing(false);
    });
  }
  const [addingSection, setAddingSection] = useState<BudgetSection | null>(null);
  const [newDesc, setNewDesc] = useState("");
  const [newCostCat, setNewCostCat] = useState<InflationType>("Other");
  const [newUnitType, setNewUnitType] = useState("Annual");
  const [newUnits, setNewUnits] = useState("");
  const [newUnitCost, setNewUnitCost] = useState("");
  // newDomain controls which per-domain card the manual row joins. "" means
  // cross-cutting (domain=null). Default tracks the active tab so adds from a
  // specific domain tab stay scoped there unless the user picks otherwise.
  const [newDomain, setNewDomain] = useState<string>(
    activeTab !== "master" ? activeTab : (budget.domains[0] ?? "")
  );
  // Cadence state for the add-line form. Defaults are seeded per section
  // when the form opens (capex → one_time M1, others → monthly).
  const [newCadence, setNewCadence] = useState<BudgetLineCadence>("monthly");
  const [newPlannedMonths, setNewPlannedMonths] = useState<number[]>([]);

  // Multi-partner: filter to the active partner first (Master = shared lines only),
  // then apply the existing domain tab filter within that slice.
  const partnerLines = !isMultiPartner
    ? lines
    : activePartner === "master"
      ? lines.filter(l => l.deliveryPartnerId == null)
      : lines.filter(l => l.deliveryPartnerId === activePartner);
  const visibleLines = activeTab === "master"
    ? partnerLines
    : partnerLines.filter(l => l.domain === activeTab || l.domain === null);

  // Roll-up across partners for the Master panel: each partner's direct Y1 total,
  // their allocated share of shared costs (by sharedPct, normalised), and total.
  const sharedTotalY1 = lines.filter(l => l.deliveryPartnerId == null).reduce((s, l) => s + l.y1Total, 0);
  const pctSum = partners.reduce((s, p) => s + (p.sharedPct || 0), 0);
  const partnerRollup = partners.map(p => {
    const direct = lines.filter(l => l.deliveryPartnerId === p.id).reduce((s, l) => s + l.y1Total, 0);
    const shareFrac = pctSum > 0 ? (p.sharedPct || 0) / pctSum : (partners.length ? 1 / partners.length : 0);
    const allocShared = Math.round(sharedTotalY1 * shareFrac);
    return { ...p, direct, allocShared, total: direct + allocShared, shareFrac };
  });
  const activePartnerRollup = partnerRollup.find(p => p.id === activePartner) ?? null;

  const grouped = SECTION_ORDER.map(sec => ({
    section: sec,
    lines: visibleLines.filter(l => l.section === sec),
  })).filter(g => g.lines.length > 0 || ["admin_salary", "admin_other", "additional"].includes(g.section));

  const sectionTotal = (sec: BudgetSection, k: BandKey) =>
    lines.filter(l => l.section === sec).reduce((s, l) => s + l[yTotalKey(k)], 0);

  const grandTotal = (k: BandKey) =>
    visibleLines.reduce((s, l) => s + l[yTotalKey(k)], 0);

  const horizonTotal = () =>
    bands.reduce((s, b) => s + grandTotal(b.k), 0);

  // Top summary box total. For multi-partner it spans the whole budget rather
  // than just the visible (shared-only on Master) lines, which otherwise reads
  // ₹0 when there are no shared/cross-cutting items.
  const summaryYearTotal = (k: BandKey): number => {
    if (!isMultiPartner) return grandTotal(k);
    if (activePartner === "master") {
      const src = activeTab === "master" ? lines : lines.filter(l => l.domain === activeTab || l.domain === null);
      return src.reduce((s, l) => s + l[yTotalKey(k)], 0);
    }
    // Partner tab: their direct lines (domain-filtered) + allocated shared (All domains only).
    const direct = visibleLines.reduce((s, l) => s + l[yTotalKey(k)], 0);
    const sharedYear = lines.filter(l => l.deliveryPartnerId == null).reduce((s, l) => s + l[yTotalKey(k)], 0);
    const alloc = activeTab === "master" ? Math.round(sharedYear * (activePartnerRollup?.shareFrac ?? 0)) : 0;
    return direct + alloc;
  };
  const summaryHorizonTotal = () => bands.reduce((s, b) => s + summaryYearTotal(b.k), 0);

  const grandTotalLabel = activeTab === "master" ? "All domains" : (domainLabels[activeTab] ?? activeTab);

  const hasInputs = (() => {
    if (!budget.inputs) return false;
    const { extraInputs, ...top } = budget.inputs as Record<string, unknown>;
    const isCountEntry = ([k, v]: [string, unknown]) => k.startsWith("n") && typeof v === "number" && v > 0;
    return Object.entries(top).some(isCountEntry) ||
      (extraInputs != null && typeof extraInputs === "object" && Object.entries(extraInputs as Record<string, unknown>).some(isCountEntry));
  })();

  const startEdit = (l: Line) => {
    setEditing(l.id);
    setEditVals({
      description: l.description,
      costCategory: l.costCategory,
      domain: l.domain,
      cadence: l.cadence,
      plannedMonths: l.plannedMonths,
      y1Units: l.y1Units, y1UnitCost: l.y1UnitCost, y1AllocPct: l.y1AllocPct,
      y2Units: l.y2Units, y2UnitCost: l.y2UnitCost, y2AllocPct: l.y2AllocPct,
      y3Units: l.y3Units, y3UnitCost: l.y3UnitCost, y3AllocPct: l.y3AllocPct,
      y4Units: l.y4Units, y4UnitCost: l.y4UnitCost, y4AllocPct: l.y4AllocPct,
      y5Units: l.y5Units, y5UnitCost: l.y5UnitCost, y5AllocPct: l.y5AllocPct,
    });
  };

  const saveEdit = (lineId: string) => {
    const updated = { ...editVals };
    // Recompute totals locally for immediate feedback
    const tot = (u?: number, c?: number, a?: number) => Math.round((u ?? 0) * (c ?? 0) * (a ?? 1));
    const totals: Partial<Line> = {
      y1Total: tot(updated.y1Units, updated.y1UnitCost, updated.y1AllocPct),
      y2Total: tot(updated.y2Units, updated.y2UnitCost, updated.y2AllocPct),
      y3Total: tot(updated.y3Units, updated.y3UnitCost, updated.y3AllocPct),
      y4Total: tot(updated.y4Units, updated.y4UnitCost, updated.y4AllocPct),
      y5Total: tot(updated.y5Units, updated.y5UnitCost, updated.y5AllocPct),
    };
    setLines(prev => prev.map(l => l.id === lineId ? { ...l, ...updated, ...totals } : l));
    setEditing(null);
    startTransition(() => updateLine(lineId, updated));
  };

  const handleDelete = (lineId: string) => {
    setLines(prev => prev.filter(l => l.id !== lineId));
    startTransition(() => deleteLine(lineId));
  };

  const handleAddLine = (section: BudgetSection) => {
    if (!newDesc.trim()) return;
    // Guardrails matching server-side normaliseCadence — block the click rather
    // than the server throw, so the partner sees the missing-month problem inline.
    if (newCadence === "one_time" && newPlannedMonths.length !== 1) return;
    if (newCadence === "seasonal" && newPlannedMonths.length < 2) return;
    // Empty string means cross-cutting (domain=null in the DB) so passes
    // through as undefined to the server action.
    const domain = newDomain || undefined;
    startTransition(async () => {
      const line = await addLine(budget.id, {
        section,
        description: newDesc.trim(),
        costCategory: newCostCat,
        unitType: newUnitType,
        domain,
        cadence: newCadence,
        plannedMonths: newPlannedMonths,
        y1Units: parseFloat(newUnits) || 0,
        y1UnitCost: parseFloat(newUnitCost) || 0,
        // Tag to the active partner so it lands on the right tab (Master = shared).
        deliveryPartnerId: isMultiPartner && activePartner !== "master" ? activePartner : null,
      });
      setLines(prev => [...prev, line as unknown as Line]);
      setAddingSection(null);
      setNewDesc(""); setNewUnits(""); setNewUnitCost("");
      setNewCadence("monthly"); setNewPlannedMonths([]);
    });
  };

  return (
    <div>
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-start gap-3 mb-6">
        <div className="flex-1 min-w-0">
          <div className="flex flex-wrap items-center gap-2">
            <h1 className="text-xl font-semibold text-stone-900">{budget.name}</h1>
            <span className={`text-xs px-2 py-0.5 rounded-full ${budget.status === "approved" ? "bg-emerald-100 text-emerald-700" : budget.status === "final" ? "bg-green-100 text-green-700" : "bg-amber-100 text-amber-700"}`}>
              {budget.status === "approved" ? "Approved" : budget.status === "final" ? "Finalized" : "Draft"}
            </span>
            {budget.importedAt && (
              <span
                className="text-xs px-2 py-0.5 rounded-full bg-sky-100 text-sky-700"
                title="Created by importing a filled Excel template. Its lines were entered/edited by hand, so any future regenerate-from-inputs would replace them."
              >
                Imported
              </span>
            )}
            <span className="text-xs text-stone-400">
              {horizonLabel(budget.horizonMonths ?? budget.years * 12)}
              {!budget.applyInflation && <span className="ml-1 text-stone-300">· flat</span>}
            </span>
          </div>
          <div className="mt-1 flex flex-wrap gap-1">
            {budget.domains.map(d => <span key={d} className="text-xs bg-stone-100 text-stone-600 px-2 py-0.5 rounded">{domainLabels[d] ?? d}</span>)}
          </div>
          <label className="mt-2 flex items-center gap-1.5 text-xs text-stone-500">
            Partner
            <select
              value={budget.grantPartnerId ?? ""}
              disabled={pending}
              onChange={e => {
                const v = e.target.value || null;
                startTransition(() => updateBudgetGrantPartner(budget.id, v));
              }}
              className="rounded border border-stone-300 px-2 py-1 text-sm text-stone-700 disabled:opacity-60"
            >
              <option value="">Unassigned</option>
              {(budget.grantPartners ?? []).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
            </select>
          </label>
        </div>
        <div className="flex flex-wrap gap-2">
          {budget.status === "approved" && (
            <a href={`/budget/${budget.id}/reports`}
              className="text-sm bg-emerald-600 text-white px-3 py-1.5 rounded-lg hover:bg-emerald-700">
              Reports
            </a>
          )}
          <a href={`/budget/${budget.id}/analysis`}
            className="text-sm border border-stone-300 px-3 py-1.5 rounded-lg hover:bg-stone-50 text-stone-700">
            Analysis
          </a>
          <button
            type="button"
            onClick={async () => {
              try {
                const res = await fetch(`/budget/${budget.id}/export`);
                if (!res.ok) { alert(`Export failed (${res.status})`); return; }
                const blob = await res.blob();
                const cd = res.headers.get("Content-Disposition") ?? "";
                const m = cd.match(/filename="?([^";]+)"?/);
                const url = URL.createObjectURL(blob);
                const a = document.createElement("a");
                a.href = url;
                a.download = m?.[1] ?? `${budget.name}_budget.xlsx`;
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
                setTimeout(() => URL.revokeObjectURL(url), 1000);
              } catch {
                alert("Export failed. Please try again.");
              }
            }}
            className="text-sm border border-stone-300 px-3 py-1.5 rounded-lg hover:bg-stone-50 text-stone-700">
            Export
          </button>
          {budget.status === "draft" && (
            <button
              onClick={() => startTransition(() => finalizeBudget(budget.id))}
              disabled={pending}
              className="text-sm bg-sky-600 text-white px-3 py-1.5 rounded-lg hover:bg-sky-700 disabled:opacity-60">
              Finalize
            </button>
          )}
        </div>
      </div>

      {/* Grand total bar */}
      {hasInputs && (
        <div className="bg-sky-50 border border-sky-200 rounded-xl px-5 py-4 mb-6 flex flex-wrap gap-6 items-start">
          <div className="self-center text-xs font-semibold text-sky-700 uppercase tracking-wide min-w-[100px]">
            {grandTotalLabel}
          </div>
          {bands.map(b => (
            <TotalCell key={b.k}
              label={`${b.label} Total`}
              value={summaryYearTotal(b.k)}
              big={b.k === 1}
            />
          ))}
          {bands.length > 1 && (
            <TotalCell label={`${horizonLabel(budget.horizonMonths ?? budget.years * 12)} Total`}
              value={summaryHorizonTotal()} big />
          )}
        </div>
      )}

      {/* Delivery-partner tabs (multi-partner budgets only) */}
      {isMultiPartner && (
        <div className="flex gap-1 mb-3 overflow-x-auto pb-1 border-b border-stone-200">
          {(["master", ...partners.map(p => p.id)]).map(pid => {
            const label = pid === "master" ? "Master" : (partners.find(p => p.id === pid)?.name ?? "Partner");
            return (
              <button key={pid} onClick={() => { setActivePartner(pid); setActiveTab("master"); }}
                className={`text-sm px-4 py-1.5 rounded-t-lg whitespace-nowrap transition-all border-b-2 ${
                  activePartner === pid ? "border-emerald-600 text-emerald-700 font-medium" : "border-transparent text-stone-500 hover:bg-stone-100"
                }`}>
                {label}
              </button>
            );
          })}
        </div>
      )}

      {/* Master roll-up across partners */}
      {isMultiPartner && activePartner === "master" && (
        <div className="bg-emerald-50 border border-emerald-200 rounded-xl px-5 py-4 mb-4 overflow-x-auto">
          <div className="text-xs font-semibold text-emerald-700 uppercase tracking-wide mb-2">Roll-up (Y1) — direct + allocated shared</div>
          <table className="text-sm min-w-[480px]">
            <thead><tr className="text-stone-500 text-xs">
              <th className="text-left pr-6 py-1">Partner</th><th className="text-right px-3">Direct</th>
              <th className="text-right px-3">Shared %</th><th className="text-right px-3">Allocated shared</th><th className="text-right pl-3">Total</th>
            </tr></thead>
            <tbody>
              {partnerRollup.map(p => (
                <tr key={p.id} className="border-t border-emerald-100">
                  <td className="pr-6 py-1">{p.name}</td>
                  <td className="text-right px-3">{fmt(p.direct)}</td>
                  <td className="text-right px-3 text-stone-500">{Math.round(p.shareFrac * 100)}%</td>
                  <td className="text-right px-3">{fmt(p.allocShared)}</td>
                  <td className="text-right pl-3 font-medium">{fmt(p.total)}</td>
                </tr>
              ))}
              <tr className="border-t-2 border-emerald-300 font-semibold">
                <td className="pr-6 py-1">All partners</td>
                <td className="text-right px-3">{fmt(partnerRollup.reduce((s, p) => s + p.direct, 0))}</td>
                <td className="text-right px-3"></td>
                <td className="text-right px-3">{fmt(sharedTotalY1)}</td>
                <td className="text-right pl-3">{fmt(partnerRollup.reduce((s, p) => s + p.total, 0))}</td>
              </tr>
            </tbody>
          </table>
          {pctSum !== 100 && partners.length > 0 && sharedTotalY1 > 0 && (
            <p className="text-xs text-amber-600 mt-2">Shared % sums to {pctSum}% (not 100) — allocations are normalised proportionally.</p>
          )}
          <p className="text-xs text-stone-400 mt-1">
            {sharedTotalY1 > 0
              ? "Lines below are the shared / cross-cutting costs (editable). Switch tabs to edit each partner's direct lines."
              : "No shared / cross-cutting costs in this budget. Switch tabs to edit each partner's direct lines."}
          </p>
        </div>
      )}

      {/* Active partner's allocated-shared note */}
      {isMultiPartner && activePartnerRollup && (
        <div className="bg-emerald-50 border border-emerald-200 rounded-xl px-5 py-3 mb-4 text-sm flex flex-wrap gap-6">
          <span><span className="text-stone-500">Direct (Y1): </span><span className="font-medium">{fmt(activePartnerRollup.direct)}</span></span>
          <span><span className="text-stone-500">+ Allocated shared ({Math.round(activePartnerRollup.shareFrac * 100)}%): </span><span className="font-medium">{fmt(activePartnerRollup.allocShared)}</span></span>
          <span><span className="text-stone-500">= Partner total: </span><span className="font-semibold">{fmt(activePartnerRollup.total)}</span></span>
        </div>
      )}

      {/* Domain tabs */}
      <div className="flex gap-1 mb-4 overflow-x-auto pb-1">
        {(["master", ...budget.domains] as const).map(tab => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`text-sm px-4 py-1.5 rounded-lg whitespace-nowrap transition-all ${
              activeTab === tab ? "bg-sky-600 text-white" : "text-stone-600 hover:bg-stone-100"
            }`}
          >
            {tab === "master" ? (isMultiPartner ? "All domains" : "Master Summary") : (domainLabels[tab] ?? tab)}
          </button>
        ))}
      </div>

      {/* Line item tables */}
      <div className="space-y-6">
        {grouped.map(({ section, lines: sLines }) => (
          <div key={section} className="bg-white border border-stone-200 rounded-xl overflow-hidden">
            <div className="flex items-center justify-between px-4 py-2.5 bg-stone-50 border-b border-stone-200">
              <span className="text-sm font-semibold text-stone-700">{SECTION_LABELS[section]}</span>
              <span className="text-sm text-stone-500">{fmt(sLines.reduce((s, l) => s + l.y1Total, 0))}</span>
            </div>

            <div className="overflow-x-auto">
            <table className="w-full min-w-[520px] text-sm">
              <thead>
                <tr className="border-b border-stone-100 text-xs text-stone-400">
                  <th className="text-left px-4 py-2 w-8">#</th>
                  <th className="text-left px-2 py-2">Description</th>
                  <th className="text-right px-2 py-2 w-20">Units</th>
                  <th className="text-right px-2 py-2 w-28">Unit Cost</th>
                  {showAlloc && <th className="text-right px-2 py-2 w-16">Alloc%</th>}
                  {bands.map(b => (
                    <th key={b.k} className="text-right px-2 py-2 w-28">{b.label}</th>
                  ))}
                  <th className="w-16 px-2 py-2"></th>
                </tr>
              </thead>
              <tbody>
                {sLines.map((l, i) => {
                  const w = working[l.id];
                  const colSpan = 5 + (showAlloc ? 1 : 0) + bands.length;
                  const isWorkOpen = workLineId === l.id;
                  const editingThis = wEditing && isWorkOpen;
                  const compSum = w ? Math.round(w.components.reduce((s, c) => s + c.qty * c.unitCost, 0)) : 0;
                  const reconciles = !w || w.components.length === 0 || compSum === Math.round(l.y1UnitCost);
                  const hist = histByLine[l.id];
                  return (
                    <Fragment key={l.id}>
                      {editing === l.id
                        ? <EditRow line={l} vals={editVals} setVals={setEditVals}
                            bands={bands} showAlloc={showAlloc} inflationRate={inflationRate}
                            domains={budget.domains} domainLabels={domainLabels}
                            onSave={() => saveEdit(l.id)} onCancel={() => setEditing(null)} />
                        : <ViewRow line={l} i={i + 1} bands={bands} showAlloc={showAlloc}
                            onEdit={() => startEdit(l)} onDelete={() => handleDelete(l.id)}
                            onWorking={() => toggleWorking(l.id)} hasWorking={!!w && w.components.length > 0} isOwnWorking={!!w?.isOwn} />
                      }
                      {isWorkOpen && (
                        <tr className="border-b border-stone-100 bg-stone-50/60">
                          <td colSpan={colSpan} className="px-4 py-3">
                            {editingThis ? (
                              <div className="mb-4">
                                <div className="text-xs font-semibold text-stone-500 mb-1.5">Edit working — components set this line’s unit cost</div>
                                <table className="w-full text-xs max-w-2xl">
                                  <thead><tr className="text-stone-400"><th className="text-left py-1 font-medium">Item</th><th className="text-left font-medium">Spec</th><th className="text-right font-medium w-16">Qty</th><th className="text-right font-medium w-24">Unit ₹</th><th className="text-right font-medium w-24">Amount ₹</th><th className="w-6" /></tr></thead>
                                  <tbody>
                                    {wRows.map((r, idx) => (
                                      <tr key={idx} className="border-t border-stone-100">
                                        <td className="py-1"><input value={r.label} onChange={e => updateWRow(idx, "label", e.target.value)} placeholder="Item" className="w-full border border-stone-200 rounded px-1.5 py-1 focus:outline-none focus:ring-1 focus:ring-sky-500" /></td>
                                        <td><input value={r.spec} onChange={e => updateWRow(idx, "spec", e.target.value)} placeholder="spec" className="w-full border border-stone-200 rounded px-1.5 py-1 focus:outline-none focus:ring-1 focus:ring-sky-500" /></td>
                                        <td><input type="number" value={r.qty} onChange={e => updateWRow(idx, "qty", e.target.value)} className="w-full border border-stone-200 rounded px-1.5 py-1 text-right focus:outline-none focus:ring-1 focus:ring-sky-500" /></td>
                                        <td><input type="number" value={r.unitCost} onChange={e => updateWRow(idx, "unitCost", e.target.value)} className="w-full border border-stone-200 rounded px-1.5 py-1 text-right focus:outline-none focus:ring-1 focus:ring-sky-500" /></td>
                                        <td className="text-right text-stone-600">{Math.round((parseFloat(r.qty) || 0) * (parseFloat(r.unitCost) || 0)).toLocaleString("en-IN")}</td>
                                        <td className="text-center"><button onClick={() => removeWRow(idx)} className="text-stone-300 hover:text-red-500">×</button></td>
                                      </tr>
                                    ))}
                                    <tr className="border-t border-stone-200 font-medium text-stone-700">
                                      <td className="py-1.5" colSpan={4}><button onClick={addWRow} className="text-xs text-sky-600 hover:text-sky-800">+ Add item</button>{wRows.length > 0 && <span className="ml-3 font-normal text-stone-500">→ unit cost becomes ₹{wRollup.toLocaleString("en-IN")}</span>}</td>
                                      <td className="text-right">{wRollup.toLocaleString("en-IN")}</td>
                                      <td />
                                    </tr>
                                  </tbody>
                                </table>
                                <div className="mt-2 max-w-2xl">
                                  <label className="text-xs text-stone-500">Derivation note (for rates that aren’t itemised)</label>
                                  <textarea value={wDeriv} onChange={e => setWDeriv(e.target.value)} rows={2} placeholder="e.g. average of 3 vendor quotes" className="mt-1 w-full text-xs border border-stone-200 rounded px-2 py-1.5 focus:outline-none focus:ring-1 focus:ring-sky-500" />
                                </div>
                                <div className="mt-2 flex gap-2">
                                  <button onClick={() => saveWorking(l)} disabled={pending} className="text-xs bg-sky-600 text-white px-3 py-1.5 rounded hover:bg-sky-700 disabled:opacity-50">{pending ? "Saving…" : "Save working"}</button>
                                  <button onClick={() => setWEditing(false)} className="text-xs text-stone-400 hover:text-stone-700">Cancel</button>
                                </div>
                              </div>
                            ) : (
                              <div className="mb-4">
                                {w && w.components.length > 0 ? (
                                  <>
                                    <div className="text-xs font-semibold text-stone-500 mb-1.5">Working — how ₹{l.y1UnitCost.toLocaleString("en-IN")} is derived {w.isOwn ? "" : <span className="text-stone-400">(standard, from registry)</span>}</div>
                                    <table className="w-full text-xs max-w-2xl">
                                      <thead><tr className="text-stone-400"><th className="text-left py-1 font-medium">Item</th><th className="text-left font-medium">Spec</th><th className="text-right font-medium">Qty</th><th className="text-right font-medium">Unit ₹</th><th className="text-right font-medium">Amount ₹</th></tr></thead>
                                      <tbody>
                                        {w.components.map((c, idx) => (
                                          <tr key={idx} className="border-t border-stone-100">
                                            <td className="py-1 text-stone-700">{c.label}</td>
                                            <td className="text-stone-400">{c.spec ?? ""}</td>
                                            <td className="text-right text-stone-600">{c.qty}</td>
                                            <td className="text-right text-stone-600">{c.unitCost.toLocaleString("en-IN")}</td>
                                            <td className="text-right text-stone-800">{Math.round(c.qty * c.unitCost).toLocaleString("en-IN")}</td>
                                          </tr>
                                        ))}
                                        <tr className="border-t border-stone-200 font-medium text-stone-700">
                                          <td className="py-1" colSpan={4}>Sub-total{!reconciles && <span className="ml-2 text-red-500 font-normal">⚠ ≠ unit cost ₹{l.y1UnitCost.toLocaleString("en-IN")}</span>}</td>
                                          <td className="text-right">{compSum.toLocaleString("en-IN")}</td>
                                        </tr>
                                      </tbody>
                                    </table>
                                  </>
                                ) : (
                                  <div className="text-xs text-stone-400">No breakup recorded for this line yet.</div>
                                )}
                                {w?.derivation && <p className="text-xs text-stone-500 mt-2 max-w-2xl"><span className="text-stone-400">Derivation:</span> {w.derivation}</p>}
                                <button onClick={() => startWEdit(l.id)} className="text-xs text-sky-600 hover:text-sky-800 mt-2">{w && (w.components.length > 0 || w.derivation) ? "Edit working" : "Add working"}</button>
                              </div>
                            )}
                            <div>
                              <div className="text-xs font-semibold text-stone-500 mb-1.5">Change history</div>
                              {!hist ? <div className="text-xs text-stone-400">{histLoading ? "Loading…" : "—"}</div>
                                : hist.length === 0 ? <div className="text-xs text-stone-400">No changes logged.</div>
                                : (
                                  <ul className="space-y-1">
                                    {hist.map(h => (
                                      <li key={h.id} className="text-xs text-stone-600 flex flex-wrap gap-x-2">
                                        <span className="text-stone-400 tabular-nums">{new Date(h.changedAt).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}</span>
                                        <span>{h.oldCost == null ? "—" : `₹${h.oldCost.toLocaleString("en-IN")}`} → {h.newCost == null ? "—" : `₹${h.newCost.toLocaleString("en-IN")}`}</span>
                                        {h.source && <span className="text-stone-400">· {h.source}</span>}
                                        {h.changedBy && <span className="text-stone-400">· {h.changedBy}</span>}
                                      </li>
                                    ))}
                                  </ul>
                                )}
                            </div>
                          </td>
                        </tr>
                      )}
                    </Fragment>
                  );
                })}
              </tbody>
              <tfoot>
                <tr className="border-t border-stone-200 bg-stone-50 font-medium text-stone-700">
                  <td className="px-4 py-2" colSpan={4 + (showAlloc ? 1 : 0)}>Section total</td>
                  {bands.map(b => (
                    <td key={b.k} className="text-right px-2 py-2">
                      {fmt(sLines.reduce((s, l) => s + l[yTotalKey(b.k)], 0))}
                    </td>
                  ))}
                  <td />
                </tr>
              </tfoot>
            </table>
            </div>

            {/* Add row button */}
            {addingSection === section ? (
              <div className="px-4 py-3 border-t border-stone-100 space-y-2">
                <div className="flex flex-wrap gap-2 items-end">
                  <input
                    autoFocus
                    value={newDesc}
                    onChange={e => setNewDesc(e.target.value)}
                    placeholder="Description"
                    className="flex-1 min-w-48 border border-stone-300 rounded px-2 py-1 text-sm focus:outline-none focus:ring-1 focus:ring-sky-500"
                  />
                  <select value={newCostCat} onChange={e => setNewCostCat(e.target.value as InflationType)}
                    className="border border-stone-300 rounded px-2 py-1 text-xs focus:outline-none">
                    <option value="Salary">Salary inflation (10%)</option>
                    <option value="Other">Other inflation (5%)</option>
                    <option value="Nil">No inflation</option>
                  </select>
                  <select value={newDomain} onChange={e => setNewDomain(e.target.value)}
                    className="border border-stone-300 rounded px-2 py-1 text-xs focus:outline-none"
                    title="Which per-domain card this row belongs to. Cross-cutting = shared admin / travel / shared.">
                    <option value="">Cross-cutting</option>
                    {budget.domains.map(d => (
                      <option key={d} value={d}>{domainLabels[d] ?? d}</option>
                    ))}
                  </select>
                  <input value={newUnitType} onChange={e => setNewUnitType(e.target.value)}
                    placeholder="Unit label" className="w-28 border border-stone-300 rounded px-2 py-1 text-xs focus:outline-none" />
                </div>
                <div className="flex flex-wrap items-center gap-2">
                  <span className="text-[10px] uppercase tracking-widest text-stone-400">Cadence</span>
                  <CadencePicker
                    cadence={newCadence}
                    plannedMonths={newPlannedMonths}
                    onChange={({ cadence, plannedMonths }) => {
                      setNewCadence(cadence);
                      setNewPlannedMonths(plannedMonths);
                    }}
                  />
                </div>
                <div className="flex flex-wrap gap-2 items-end">
                  <input type="number" value={newUnits} onChange={e => setNewUnits(e.target.value)}
                    placeholder="Units (Y1)" className="w-28 border border-stone-300 rounded px-2 py-1 text-sm focus:outline-none" />
                  <input type="number" value={newUnitCost} onChange={e => setNewUnitCost(e.target.value)}
                    placeholder="Unit cost ₹ (Y1)" className="w-36 border border-stone-300 rounded px-2 py-1 text-sm focus:outline-none" />
                  {newUnits && newUnitCost && (
                    <span className="text-xs text-stone-500">
                      Y1: ₹{Math.round((parseFloat(newUnits)||0)*(parseFloat(newUnitCost)||0)*bands[0].factor).toLocaleString("en-IN")}
                      {showExtraBands && (() => {
                        const rate = inflationRate[newCostCat];
                        const u = parseFloat(newUnits) || 0;
                        const c = parseFloat(newUnitCost) || 0;
                        return bands.slice(1).map(b => {
                          const yc = c * Math.pow(1 + rate, b.k - 1);
                          const yt = Math.round(u * yc * b.factor);
                          return <Fragment key={b.k}> · {b.label}: ₹{yt.toLocaleString("en-IN")}</Fragment>;
                        });
                      })()}
                    </span>
                  )}
                  <div className="flex gap-2 ml-auto">
                    <button onClick={() => handleAddLine(section)} disabled={!newDesc.trim() || pending}
                      className="text-xs bg-sky-600 text-white px-3 py-1.5 rounded hover:bg-sky-700 disabled:opacity-50">Add</button>
                    <button onClick={() => setAddingSection(null)} className="text-xs text-stone-400 hover:text-stone-700">Cancel</button>
                  </div>
                </div>
              </div>
            ) : (
              <button
                onClick={() => {
                  setAddingSection(section);
                  // Refresh the default each time the form opens so it tracks
                  // whichever tab the user is currently focused on.
                  setNewDomain(activeTab !== "master" ? activeTab : (budget.domains[0] ?? ""));
                  // Section-default cadence: Capex defaults to one_time month 1.
                  // Every other section starts as monthly — partner marks camps / TLM by hand.
                  if (section === "capex") {
                    setNewCadence("one_time");
                    setNewPlannedMonths([1]);
                  } else {
                    setNewCadence("monthly");
                    setNewPlannedMonths([]);
                  }
                }}
                className="w-full text-left px-4 py-2 text-xs text-stone-400 hover:text-sky-600 hover:bg-sky-50 border-t border-stone-100 transition-colors">
                + Add line
              </button>
            )}
          </div>
        ))}
      </div>

      {/* Grand total footer */}
      {hasInputs && (
        <div className="mt-6 bg-stone-900 text-white rounded-xl px-5 py-4 flex flex-wrap gap-6 items-start">
          <div className="self-center">
            <div className="text-xs text-stone-400 uppercase tracking-wide">Grand Total</div>
            <div className="text-sm font-semibold text-white">{grandTotalLabel}</div>
          </div>
          {bands.map(b => (
            <TotalCell key={b.k} label={b.label} value={grandTotal(b.k)} big={b.k === 1} white />
          ))}
          {bands.length > 1 && (
            <TotalCell label={`${horizonLabel(budget.horizonMonths ?? budget.years * 12)} Total`}
              value={horizonTotal()} big white />
          )}
        </div>
      )}
    </div>
  );
}

function TotalCell({ label, value, big, white }: { label: string; value: number; big?: boolean; white?: boolean }) {
  return (
    <div>
      <div className={`text-xs ${white ? "text-stone-400" : "text-stone-500"}`}>{label}</div>
      <div className={`font-semibold ${big ? "text-xl" : "text-base"} ${white ? "text-white" : "text-stone-900"}`}>
        ₹{(value / 100000).toFixed(2)}L
      </div>
    </div>
  );
}

function ViewRow({ line, i, bands, showAlloc, onEdit, onDelete, onWorking, hasWorking, isOwnWorking }: {
  line: Line; i: number; bands: Band[]; showAlloc: boolean;
  onEdit: () => void; onDelete: () => void;
  onWorking: () => void; hasWorking: boolean; isOwnWorking: boolean;
}) {
  const [showDelete, setShowDelete] = useState(false);
  return (
    <tr className="border-b border-stone-50 hover:bg-stone-50 group">
      <td className="px-4 py-2 text-stone-400 text-xs">{i}</td>
      <td className="px-2 py-2">
        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-stone-800">{line.description}</span>
          <span className={`text-xs px-1.5 py-0.5 rounded ${INFLATION_BADGE[line.costCategory]}`}>{line.costCategory}</span>
          {hasWorking && (
            <button onClick={onWorking} className={`text-[10px] px-1.5 py-0.5 rounded border ${isOwnWorking ? "bg-emerald-50 text-emerald-600 border-emerald-100" : "bg-sky-50 text-sky-600 border-sky-100"}`} title={isOwnWorking ? "Custom working on this budget" : "Standard working from the cost registry"}>
              working{isOwnWorking ? " ✎" : ""}
            </button>
          )}
          {line.cadence !== "monthly" && line.plannedMonths.length > 0 && (
            <span
              title={`${CADENCE_LABELS[line.cadence]} · planned in month${line.plannedMonths.length > 1 ? "s" : ""} ${line.plannedMonths.join(", ")} of the grant year`}
              className="text-[10px] uppercase tracking-wide text-stone-500 bg-stone-100 px-1.5 py-0.5 rounded"
            >
              Planned: {formatPlannedMonths(line.plannedMonths)}
            </span>
          )}
          {line.salaryHint && line.y1UnitCost === 0 && (
            <span className="text-xs text-amber-600 italic">hint: {line.salaryHint}</span>
          )}
        </div>
        {line.notes && <div className="text-xs text-stone-400 mt-0.5">{line.notes}</div>}
      </td>
      <td className="text-right px-2 py-2 text-stone-500 text-xs">{line.y1Units > 0 ? line.y1Units : "–"}</td>
      <td className="text-right px-2 py-2 text-stone-500 text-xs">{line.y1UnitCost > 0 ? `₹${line.y1UnitCost.toLocaleString("en-IN")}` : "–"}</td>
      {showAlloc && <td className="text-right px-2 py-2 text-stone-400 text-xs">{line.y1AllocPct < 1 ? `${(line.y1AllocPct * 100).toFixed(0)}%` : "100%"}</td>}
      {bands.map(b => {
        const total = line[yTotalKey(b.k)];
        const isFirst = b.k === 1;
        return (
          <td key={b.k}
            className={`text-right px-2 py-2 ${isFirst ? `font-medium ${total === 0 ? "text-amber-500" : "text-stone-900"}` : "text-stone-600"}`}>
            {fmt(total)}
          </td>
        );
      })}
      <td className="px-2 py-2">
        <div className="flex gap-1 opacity-100 sm:opacity-0 sm:group-hover:opacity-100 transition-opacity">
          <button onClick={onEdit} className="text-xs text-sky-600 hover:text-sky-800">Edit</button>
          <button onClick={onWorking} className="text-xs text-stone-400 hover:text-stone-700" title="Working &amp; history">₹⋯</button>
          {!line.isAutoGenerated && (
            showDelete
              ? <button onClick={onDelete} className="text-xs text-red-600 hover:text-red-800">Confirm</button>
              : <button onClick={() => setShowDelete(true)} className="text-xs text-stone-400 hover:text-red-500">Del</button>
          )}
        </div>
      </td>
    </tr>
  );
}

function EditRow({ line, vals, setVals, bands, showAlloc, inflationRate, domains, domainLabels, onSave, onCancel }: {
  line: Line; vals: Partial<Line>; setVals: (v: Partial<Line>) => void;
  bands: Band[]; showAlloc: boolean; inflationRate: Record<InflationType, number>;
  domains: string[]; domainLabels: Record<string, string>;
  onSave: () => void; onCancel: () => void;
}) {
  // Switching the inflation category re-inflates the out-year unit costs from Y1
  // at the new category's rate (no-op when applyInflation is off → rate 0).
  const setCostCategory = (cat: InflationType) => {
    const rate = inflationRate[cat] ?? 0;
    const y1c  = vals.y1UnitCost ?? line.y1UnitCost ?? 0;
    const next: Partial<Line> = { ...vals, costCategory: cat };
    for (const b of bands) {
      if (b.k === 1) continue;
      next[yCostKey(b.k)] = Math.round(y1c * Math.pow(1 + rate, b.k - 1));
    }
    setVals(next);
  };
  // Edit row keeps inflation-aware auto-fill but uses zero rate when applyInflation
  // is off (band.factor stays 1 in those cases). The parent already gates extra
  // bands on showAlloc / bands.length.
  const setY1Units = (v: number) => {
    const next: Partial<Line> = { ...vals, y1Units: v };
    for (const b of bands) {
      if (b.k === 1) continue;
      next[yUnitsKey(b.k)] = v * b.factor;
    }
    setVals(next);
  };

  const setY1UnitCost = (v: number) => {
    const next: Partial<Line> = { ...vals, y1UnitCost: v };
    // Re-compute Y2..Y5 from existing cost ratio. Use a conservative inflation
    // pass: same rate per year as the line's current Y1→Y2 step.
    const ratio = line.y1UnitCost > 0 ? line.y2UnitCost / line.y1UnitCost : 1;
    let cur = v;
    for (const b of bands) {
      if (b.k === 1) continue;
      cur = Math.round(cur * ratio);
      next[yCostKey(b.k)] = cur;
    }
    setVals(next);
  };

  const preview = (k: BandKey) =>
    Math.round((vals[yUnitsKey(k)] ?? 0) * (vals[yCostKey(k)] ?? 0) * (vals[yAllocKey(k)] ?? 1));

  return (
    <tr className="border-b border-sky-100 bg-sky-50">
      <td className="px-4 py-2 text-stone-400 text-xs">✏</td>
      <td className="px-2 py-1.5">
        <input
          value={vals.description ?? ""}
          onChange={e => setVals({ ...vals, description: e.target.value })}
          className="w-full border border-sky-300 rounded px-2 py-1 text-sm focus:outline-none focus:ring-1 focus:ring-sky-500"
        />
        <div className="flex items-center gap-2 mt-1 flex-wrap">
          <span className="text-[10px] uppercase tracking-widest text-stone-400">Domain</span>
          <select value={vals.domain ?? ""}
            onChange={e => setVals({ ...vals, domain: e.target.value === "" ? null : e.target.value })}
            className="border border-sky-200 rounded px-1.5 py-0.5 text-xs focus:outline-none focus:ring-1 focus:ring-sky-500 bg-white">
            <option value="">Cross-cutting</option>
            {domains.map(d => (
              <option key={d} value={d}>{domainLabels[d] ?? d}</option>
            ))}
          </select>
        </div>
        <div className="flex items-center gap-2 mt-1 flex-wrap">
          <span className="text-[10px] uppercase tracking-widest text-stone-400">Inflation</span>
          <select value={vals.costCategory ?? line.costCategory}
            onChange={e => setCostCategory(e.target.value as InflationType)}
            className="border border-sky-200 rounded px-1.5 py-0.5 text-xs focus:outline-none focus:ring-1 focus:ring-sky-500 bg-white"
            title="Which inflation category this line compounds at. Changing it re-inflates the out-year unit costs.">
            {(["Salary", "Other", "Nil"] as InflationType[]).map(cat => {
              const pct = Math.round((inflationRate[cat] ?? 0) * 100);
              return <option key={cat} value={cat}>{cat === "Nil" ? "No inflation" : `${cat}${pct > 0 ? ` (${pct}%)` : ""}`}</option>;
            })}
          </select>
        </div>
        <div className="flex items-center gap-2 mt-1 flex-wrap">
          <span className="text-[10px] uppercase tracking-widest text-stone-400">Cadence</span>
          <CadencePicker
            cadence={vals.cadence ?? line.cadence}
            plannedMonths={vals.plannedMonths ?? line.plannedMonths}
            onChange={({ cadence, plannedMonths }) => setVals({ ...vals, cadence, plannedMonths })}
          />
        </div>
        {line.salaryHint && <p className="text-xs text-amber-600 mt-0.5">Suggested: {line.salaryHint}</p>}
      </td>
      <td className="px-2 py-1.5">
        <input type="number" value={vals.y1Units || ""} placeholder="Units"
          onChange={e => setY1Units(parseFloat(e.target.value) || 0)}
          className="w-full border border-sky-300 rounded px-2 py-1 text-sm text-right focus:outline-none" />
      </td>
      <td className="px-2 py-1.5">
        <input type="number" value={vals.y1UnitCost || ""} placeholder="Unit cost"
          onChange={e => setY1UnitCost(parseFloat(e.target.value) || 0)}
          className="w-full border border-sky-300 rounded px-2 py-1 text-sm text-right focus:outline-none" />
      </td>
      {showAlloc && (
        <td className="px-2 py-1.5">
          <input type="number" value={(vals.y1AllocPct ?? 1) * 100 || ""} step="0.1"
            onChange={e => setVals({ ...vals, y1AllocPct: (parseFloat(e.target.value) || 100) / 100 })}
            className="w-full border border-sky-300 rounded px-2 py-1 text-xs text-right focus:outline-none" />
        </td>
      )}
      {bands.map(b => b.k === 1 ? (
        <td key={b.k} className="text-right px-2 py-1.5 font-medium text-sky-700">{fmt(preview(1))}</td>
      ) : (
        <td key={b.k} className="px-2 py-1.5">
          <input type="number" value={vals[yCostKey(b.k)] || ""} placeholder={`${b.label} cost`}
            onChange={e => setVals({ ...vals, [yCostKey(b.k)]: parseFloat(e.target.value) || 0 })}
            className="w-full border border-sky-200 rounded px-1.5 py-0.5 text-xs text-right focus:outline-none" />
          <div className="text-right text-xs text-sky-600 mt-0.5">{fmt(preview(b.k))}</div>
        </td>
      ))}
      <td className="px-2 py-1.5">
        <div className="flex gap-1">
          <button onClick={onSave} className="text-xs bg-sky-600 text-white px-2 py-0.5 rounded hover:bg-sky-700">Save</button>
          <button onClick={onCancel} className="text-xs text-stone-400 hover:text-stone-700">×</button>
        </div>
      </td>
    </tr>
  );
}
