"use client";

import { useState, useTransition, useRef } from "react";
import { updateLine, addLine, deleteLine, finalizeBudget, deleteBudget } from "../actions";
import type { BudgetDomain, BudgetSection, InflationType } from "@/app/generated/prisma/client";

type Line = {
  id: string;
  domain: BudgetDomain | null;
  section: BudgetSection;
  position: number;
  description: string;
  costCategory: InflationType;
  unitType: string;
  isAutoGenerated: boolean;
  salaryHint: string | null;
  notes: string | null;
  y1Units: number; y1UnitCost: number; y1AllocPct: number; y1Total: number;
  y2Units: number; y2UnitCost: number; y2AllocPct: number; y2Total: number;
  y3Units: number; y3UnitCost: number; y3AllocPct: number; y3Total: number;
};

type Budget = {
  id: string;
  name: string;
  domains: BudgetDomain[];
  years: number;
  status: "draft" | "final";
  lines: Line[];
};

const DOMAIN_LABELS: Record<string, string> = {
  Children: "Children", Youth: "Youth", Elderly: "Elderly + Kitchen",
  WelfareRights: "Welfare Rights", Creche: "Creche",
};

const SECTION_LABELS: Record<BudgetSection, string> = {
  salary: "1. Salary & Honorarium",
  capex: "2. Fixed Assets / CAPEX",
  travel: "3. Travel",
  programme: "4. Programme Expenses",
  admin_salary: "5a. Admin – Salaries",
  admin_other: "5b. Admin – Other",
  additional: "6. Additional Items",
};

const SECTION_ORDER: BudgetSection[] = ["salary", "capex", "travel", "programme", "admin_salary", "admin_other", "additional"];

const INFLATION_BADGE: Record<InflationType, string> = {
  Salary: "bg-violet-100 text-violet-700",
  Other: "bg-sky-100 text-sky-700",
  Nil: "bg-stone-100 text-stone-500",
};

const INFLATION_RATE: Record<InflationType, number> = { Salary: 0.10, Other: 0.05, Nil: 0.00 };

const fmt = (n: number) => n === 0 ? "–" : `₹${n.toLocaleString("en-IN")}`;

export default function BudgetEditor({ budget }: { budget: Budget }) {
  const [activeTab, setActiveTab] = useState<"master" | BudgetDomain>("master");
  const [lines, setLines] = useState<Line[]>(budget.lines);
  const [editing, setEditing] = useState<string | null>(null);
  const [editVals, setEditVals] = useState<Partial<Line>>({});
  const [pending, startTransition] = useTransition();
  const [addingSection, setAddingSection] = useState<BudgetSection | null>(null);
  const [newDesc, setNewDesc] = useState("");
  const [newCostCat, setNewCostCat] = useState<InflationType>("Other");
  const [newUnitType, setNewUnitType] = useState("Annual");
  const [newUnits, setNewUnits] = useState("");
  const [newUnitCost, setNewUnitCost] = useState("");

  const visibleLines = activeTab === "master"
    ? lines
    : lines.filter(l => l.domain === activeTab || l.domain === null);

  const grouped = SECTION_ORDER.map(sec => ({
    section: sec,
    lines: visibleLines.filter(l => l.section === sec),
  })).filter(g => g.lines.length > 0 || ["admin_salary", "admin_other", "additional"].includes(g.section));

  const sectionTotal = (sec: BudgetSection, yr: "y1" | "y2" | "y3") =>
    lines.filter(l => l.section === sec).reduce((s, l) => s + l[`${yr}Total`], 0);

  const grandTotal = (yr: "y1" | "y2" | "y3") =>
    lines.reduce((s, l) => s + l[`${yr}Total`], 0);

  const startEdit = (l: Line) => {
    setEditing(l.id);
    setEditVals({
      description: l.description,
      y1Units: l.y1Units, y1UnitCost: l.y1UnitCost, y1AllocPct: l.y1AllocPct,
      y2Units: l.y2Units, y2UnitCost: l.y2UnitCost, y2AllocPct: l.y2AllocPct,
      y3Units: l.y3Units, y3UnitCost: l.y3UnitCost, y3AllocPct: l.y3AllocPct,
    });
  };

  const saveEdit = (lineId: string) => {
    const updated = { ...editVals };
    // Recompute totals locally for immediate feedback
    const y1Total = Math.round((updated.y1Units ?? 0) * (updated.y1UnitCost ?? 0) * (updated.y1AllocPct ?? 1));
    const y2Total = Math.round((updated.y2Units ?? 0) * (updated.y2UnitCost ?? 0) * (updated.y2AllocPct ?? 1));
    const y3Total = Math.round((updated.y3Units ?? 0) * (updated.y3UnitCost ?? 0) * (updated.y3AllocPct ?? 1));
    setLines(prev => prev.map(l => l.id === lineId ? { ...l, ...updated, y1Total, y2Total, y3Total } : l));
    setEditing(null);
    startTransition(() => updateLine(lineId, updated));
  };

  const handleDelete = (lineId: string) => {
    setLines(prev => prev.filter(l => l.id !== lineId));
    startTransition(() => deleteLine(lineId));
  };

  const handleAddLine = (section: BudgetSection) => {
    if (!newDesc.trim()) return;
    const domain = activeTab === "master" ? undefined : activeTab as BudgetDomain;
    startTransition(async () => {
      const line = await addLine(budget.id, {
        section,
        description: newDesc.trim(),
        costCategory: newCostCat,
        unitType: newUnitType,
        domain,
        y1Units: parseFloat(newUnits) || 0,
        y1UnitCost: parseFloat(newUnitCost) || 0,
      });
      setLines(prev => [...prev, line as unknown as Line]);
      setAddingSection(null);
      setNewDesc(""); setNewUnits(""); setNewUnitCost("");
    });
  };

  return (
    <div>
      {/* Header */}
      <div className="flex items-start justify-between mb-6 gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-semibold text-stone-900">{budget.name}</h1>
            <span className={`text-xs px-2 py-0.5 rounded-full ${budget.status === "final" ? "bg-green-100 text-green-700" : "bg-amber-100 text-amber-700"}`}>
              {budget.status === "final" ? "Finalized" : "Draft"}
            </span>
            <span className="text-xs text-stone-400">{budget.years === 3 ? "3-year" : "1-year"}</span>
          </div>
          <div className="mt-1 flex flex-wrap gap-1">
            {budget.domains.map(d => <span key={d} className="text-xs bg-stone-100 text-stone-600 px-2 py-0.5 rounded">{DOMAIN_LABELS[d]}</span>)}
          </div>
        </div>
        <div className="flex gap-2 shrink-0">
          <a href={`/budget/${budget.id}/analysis`}
            className="text-sm border border-stone-300 px-3 py-1.5 rounded-lg hover:bg-stone-50 text-stone-700">
            Analysis
          </a>
          <a href={`/budget/${budget.id}/export`} target="_blank"
            className="text-sm border border-stone-300 px-3 py-1.5 rounded-lg hover:bg-stone-50 text-stone-700">
            Export Excel
          </a>
          {budget.status === "draft" && (
            <button
              onClick={() => startTransition(() => finalizeBudget(budget.id))}
              disabled={pending}
              className="text-sm bg-sky-600 text-white px-3 py-1.5 rounded-lg hover:bg-sky-700 disabled:opacity-60">
              Finalize
            </button>
          )}
        </div>
      </div>

      {/* Grand total bar */}
      <div className="bg-sky-50 border border-sky-200 rounded-xl px-5 py-4 mb-6 flex flex-wrap gap-6">
        <TotalCell label="Year 1 Total" value={grandTotal("y1")} big />
        {budget.years === 3 && <>
          <TotalCell label="Year 2 Total" value={grandTotal("y2")} />
          <TotalCell label="Year 3 Total" value={grandTotal("y3")} />
          <TotalCell label="3-Year Total" value={grandTotal("y1") + grandTotal("y2") + grandTotal("y3")} big />
        </>}
      </div>

      {/* Domain tabs */}
      <div className="flex gap-1 mb-4 overflow-x-auto pb-1">
        {(["master", ...budget.domains] as const).map(tab => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`text-sm px-4 py-1.5 rounded-lg whitespace-nowrap transition-all ${
              activeTab === tab ? "bg-sky-600 text-white" : "text-stone-600 hover:bg-stone-100"
            }`}
          >
            {tab === "master" ? "Master Summary" : DOMAIN_LABELS[tab as BudgetDomain]}
          </button>
        ))}
      </div>

      {/* Line item tables */}
      <div className="space-y-6">
        {grouped.map(({ section, lines: sLines }) => (
          <div key={section} className="bg-white border border-stone-200 rounded-xl overflow-hidden">
            <div className="flex items-center justify-between px-4 py-2.5 bg-stone-50 border-b border-stone-200">
              <span className="text-sm font-semibold text-stone-700">{SECTION_LABELS[section]}</span>
              <span className="text-sm text-stone-500">{fmt(sLines.reduce((s, l) => s + l.y1Total, 0))}</span>
            </div>

            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-stone-100 text-xs text-stone-400">
                  <th className="text-left px-4 py-2 w-8">#</th>
                  <th className="text-left px-2 py-2">Description</th>
                  <th className="text-right px-2 py-2 w-20">Units</th>
                  <th className="text-right px-2 py-2 w-28">Unit Cost</th>
                  {budget.years === 3 && <th className="text-right px-2 py-2 w-16">Alloc%</th>}
                  <th className="text-right px-2 py-2 w-28">Year 1</th>
                  {budget.years === 3 && <>
                    <th className="text-right px-2 py-2 w-28">Year 2</th>
                    <th className="text-right px-2 py-2 w-28">Year 3</th>
                  </>}
                  <th className="w-16 px-2 py-2"></th>
                </tr>
              </thead>
              <tbody>
                {sLines.map((l, i) => (
                  editing === l.id
                    ? <EditRow key={l.id} line={l} vals={editVals} setVals={setEditVals} years={budget.years}
                        onSave={() => saveEdit(l.id)} onCancel={() => setEditing(null)} />
                    : <ViewRow key={l.id} line={l} i={i + 1} years={budget.years}
                        onEdit={() => startEdit(l)} onDelete={() => handleDelete(l.id)} />
                ))}
              </tbody>
              <tfoot>
                <tr className="border-t border-stone-200 bg-stone-50 font-medium text-stone-700">
                  <td className="px-4 py-2" colSpan={budget.years === 3 ? 5 : 4}>Section total</td>
                  <td className="text-right px-2 py-2">{fmt(sLines.reduce((s, l) => s + l.y1Total, 0))}</td>
                  {budget.years === 3 && <>
                    <td className="text-right px-2 py-2">{fmt(sLines.reduce((s, l) => s + l.y2Total, 0))}</td>
                    <td className="text-right px-2 py-2">{fmt(sLines.reduce((s, l) => s + l.y3Total, 0))}</td>
                  </>}
                  <td />
                </tr>
              </tfoot>
            </table>

            {/* Add row button */}
            {addingSection === section ? (
              <div className="px-4 py-3 border-t border-stone-100 space-y-2">
                <div className="flex flex-wrap gap-2 items-end">
                  <input
                    autoFocus
                    value={newDesc}
                    onChange={e => setNewDesc(e.target.value)}
                    placeholder="Description"
                    className="flex-1 min-w-48 border border-stone-300 rounded px-2 py-1 text-sm focus:outline-none focus:ring-1 focus:ring-sky-500"
                  />
                  <select value={newCostCat} onChange={e => setNewCostCat(e.target.value as InflationType)}
                    className="border border-stone-300 rounded px-2 py-1 text-xs focus:outline-none">
                    <option value="Salary">Salary inflation (10%)</option>
                    <option value="Other">Other inflation (5%)</option>
                    <option value="Nil">No inflation</option>
                  </select>
                  <input value={newUnitType} onChange={e => setNewUnitType(e.target.value)}
                    placeholder="Unit label" className="w-28 border border-stone-300 rounded px-2 py-1 text-xs focus:outline-none" />
                </div>
                <div className="flex flex-wrap gap-2 items-end">
                  <input type="number" value={newUnits} onChange={e => setNewUnits(e.target.value)}
                    placeholder="Units (Y1)" className="w-28 border border-stone-300 rounded px-2 py-1 text-sm focus:outline-none" />
                  <input type="number" value={newUnitCost} onChange={e => setNewUnitCost(e.target.value)}
                    placeholder="Unit cost ₹ (Y1)" className="w-36 border border-stone-300 rounded px-2 py-1 text-sm focus:outline-none" />
                  {newUnits && newUnitCost && (
                    <span className="text-xs text-stone-500">
                      Y1: ₹{Math.round((parseFloat(newUnits)||0)*(parseFloat(newUnitCost)||0)).toLocaleString("en-IN")}
                      {budget.years === 3 && (() => {
                        const rate = INFLATION_RATE[newCostCat];
                        const y2c = Math.round((parseFloat(newUnitCost)||0) * (1+rate));
                        const y2t = Math.round((parseFloat(newUnits)||0) * y2c);
                        return <> · Y2: ₹{y2t.toLocaleString("en-IN")}</>;
                      })()}
                    </span>
                  )}
                  <div className="flex gap-2 ml-auto">
                    <button onClick={() => handleAddLine(section)} disabled={!newDesc.trim() || pending}
                      className="text-xs bg-sky-600 text-white px-3 py-1.5 rounded hover:bg-sky-700 disabled:opacity-50">Add</button>
                    <button onClick={() => setAddingSection(null)} className="text-xs text-stone-400 hover:text-stone-700">Cancel</button>
                  </div>
                </div>
              </div>
            ) : (
              <button
                onClick={() => setAddingSection(section)}
                className="w-full text-left px-4 py-2 text-xs text-stone-400 hover:text-sky-600 hover:bg-sky-50 border-t border-stone-100 transition-colors">
                + Add line
              </button>
            )}
          </div>
        ))}
      </div>

      {/* Grand total footer */}
      <div className="mt-6 bg-stone-900 text-white rounded-xl px-5 py-4 flex flex-wrap gap-6">
        <TotalCell label="GRAND TOTAL — Year 1" value={grandTotal("y1")} big white />
        {budget.years === 3 && <>
          <TotalCell label="Year 2" value={grandTotal("y2")} white />
          <TotalCell label="Year 3" value={grandTotal("y3")} white />
          <TotalCell label="3-Year Total" value={grandTotal("y1") + grandTotal("y2") + grandTotal("y3")} big white />
        </>}
      </div>
    </div>
  );
}

function TotalCell({ label, value, big, white }: { label: string; value: number; big?: boolean; white?: boolean }) {
  return (
    <div>
      <div className={`text-xs ${white ? "text-stone-400" : "text-stone-500"}`}>{label}</div>
      <div className={`font-semibold ${big ? "text-xl" : "text-base"} ${white ? "text-white" : "text-stone-900"}`}>
        ₹{(value / 100000).toFixed(2)}L
      </div>
    </div>
  );
}

function ViewRow({ line, i, years, onEdit, onDelete }: {
  line: Line; i: number; years: number; onEdit: () => void; onDelete: () => void;
}) {
  const [showDelete, setShowDelete] = useState(false);
  return (
    <tr className="border-b border-stone-50 hover:bg-stone-50 group">
      <td className="px-4 py-2 text-stone-400 text-xs">{i}</td>
      <td className="px-2 py-2">
        <div className="flex items-center gap-2">
          <span className="text-stone-800">{line.description}</span>
          <span className={`text-xs px-1.5 py-0.5 rounded ${INFLATION_BADGE[line.costCategory]}`}>{line.costCategory}</span>
          {line.salaryHint && line.y1UnitCost === 0 && (
            <span className="text-xs text-amber-600 italic">hint: {line.salaryHint}</span>
          )}
        </div>
        {line.notes && <div className="text-xs text-stone-400 mt-0.5">{line.notes}</div>}
      </td>
      <td className="text-right px-2 py-2 text-stone-500 text-xs">{line.y1Units > 0 ? line.y1Units : "–"}</td>
      <td className="text-right px-2 py-2 text-stone-500 text-xs">{line.y1UnitCost > 0 ? `₹${line.y1UnitCost.toLocaleString("en-IN")}` : "–"}</td>
      {years === 3 && <td className="text-right px-2 py-2 text-stone-400 text-xs">{line.y1AllocPct < 1 ? `${(line.y1AllocPct * 100).toFixed(0)}%` : "100%"}</td>}
      <td className={`text-right px-2 py-2 font-medium ${line.y1Total === 0 ? "text-amber-500" : "text-stone-900"}`}>{fmt(line.y1Total)}</td>
      {years === 3 && <>
        <td className="text-right px-2 py-2 text-stone-600">{fmt(line.y2Total)}</td>
        <td className="text-right px-2 py-2 text-stone-600">{fmt(line.y3Total)}</td>
      </>}
      <td className="px-2 py-2">
        <div className="flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
          <button onClick={onEdit} className="text-xs text-sky-600 hover:text-sky-800">Edit</button>
          {!line.isAutoGenerated && (
            showDelete
              ? <button onClick={onDelete} className="text-xs text-red-600 hover:text-red-800">Confirm</button>
              : <button onClick={() => setShowDelete(true)} className="text-xs text-stone-400 hover:text-red-500">Del</button>
          )}
        </div>
      </td>
    </tr>
  );
}

function EditRow({ line, vals, setVals, years, onSave, onCancel }: {
  line: Line; vals: Partial<Line>; setVals: (v: Partial<Line>) => void;
  years: number; onSave: () => void; onCancel: () => void;
}) {
  const rate = INFLATION_RATE[line.costCategory];

  const setY1Units = (v: number) =>
    setVals({ ...vals, y1Units: v, y2Units: v, y3Units: v });

  const setY1UnitCost = (v: number) => {
    const y2c = Math.round(v * (1 + rate));
    const y3c = Math.round(y2c * (1 + rate));
    setVals({ ...vals, y1UnitCost: v, y2UnitCost: y2c, y3UnitCost: y3c });
  };

  const previewY1 = Math.round((vals.y1Units ?? 0) * (vals.y1UnitCost ?? 0) * (vals.y1AllocPct ?? 1));
  const previewY2 = Math.round((vals.y2Units ?? 0) * (vals.y2UnitCost ?? 0) * (vals.y2AllocPct ?? 1));
  const previewY3 = Math.round((vals.y3Units ?? 0) * (vals.y3UnitCost ?? 0) * (vals.y3AllocPct ?? 1));

  return (
    <tr className="border-b border-sky-100 bg-sky-50">
      <td className="px-4 py-2 text-stone-400 text-xs">✏</td>
      <td className="px-2 py-1.5">
        <input
          value={vals.description ?? ""}
          onChange={e => setVals({ ...vals, description: e.target.value })}
          className="w-full border border-sky-300 rounded px-2 py-1 text-sm focus:outline-none focus:ring-1 focus:ring-sky-500"
        />
        {line.salaryHint && <p className="text-xs text-amber-600 mt-0.5">Suggested: {line.salaryHint}</p>}
      </td>
      <td className="px-2 py-1.5">
        <input type="number" value={vals.y1Units || ""} placeholder="Units"
          onChange={e => setY1Units(parseFloat(e.target.value) || 0)}
          className="w-full border border-sky-300 rounded px-2 py-1 text-sm text-right focus:outline-none" />
      </td>
      <td className="px-2 py-1.5">
        <input type="number" value={vals.y1UnitCost || ""} placeholder="Unit cost"
          onChange={e => setY1UnitCost(parseFloat(e.target.value) || 0)}
          className="w-full border border-sky-300 rounded px-2 py-1 text-sm text-right focus:outline-none" />
      </td>
      {years === 3 && (
        <td className="px-2 py-1.5">
          <input type="number" value={(vals.y1AllocPct ?? 1) * 100 || ""} step="0.1"
            onChange={e => setVals({ ...vals, y1AllocPct: (parseFloat(e.target.value) || 100) / 100 })}
            className="w-full border border-sky-300 rounded px-2 py-1 text-xs text-right focus:outline-none" />
        </td>
      )}
      <td className="text-right px-2 py-1.5 font-medium text-sky-700">{fmt(previewY1)}</td>
      {years === 3 && <>
        <td className="px-2 py-1.5">
          <input type="number" value={vals.y2UnitCost || ""} placeholder="Y2 cost"
            onChange={e => setVals({ ...vals, y2UnitCost: parseFloat(e.target.value) || 0 })}
            className="w-full border border-sky-200 rounded px-1.5 py-0.5 text-xs text-right focus:outline-none" />
          <div className="text-right text-xs text-sky-600 mt-0.5">{fmt(previewY2)}</div>
        </td>
        <td className="px-2 py-1.5">
          <input type="number" value={vals.y3UnitCost || ""} placeholder="Y3 cost"
            onChange={e => setVals({ ...vals, y3UnitCost: parseFloat(e.target.value) || 0 })}
            className="w-full border border-sky-200 rounded px-1.5 py-0.5 text-xs text-right focus:outline-none" />
          <div className="text-right text-xs text-sky-600 mt-0.5">{fmt(previewY3)}</div>
        </td>
      </>}
      <td className="px-2 py-1.5">
        <div className="flex gap-1">
          <button onClick={onSave} className="text-xs bg-sky-600 text-white px-2 py-0.5 rounded hover:bg-sky-700">Save</button>
          <button onClick={onCancel} className="text-xs text-stone-400 hover:text-stone-700">×</button>
        </div>
      </td>
    </tr>
  );
}
