"use server";

import { auth } from "@/lib/auth";
import prisma from "@/lib/prisma";
import { getDefaultsForCity } from "@/lib/budget-costs";
import type { BudgetDomain, BudgetSection, InflationType } from "@/app/generated/prisma/client";
import { revalidatePath } from "next/cache";

export async function seedCostRegistry(city = "Bangalore") {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const defaults = getDefaultsForCity(city);
  await prisma.$transaction(
    defaults.map(c =>
      prisma.costRegistry.upsert({
        where: { city_itemKey: { city, itemKey: c.itemKey } },
        create: {
          city,
          domain: c.domain ?? undefined,
          itemKey: c.itemKey,
          unitCost: c.unitCost,
          unit: c.unit,
          effectiveYear: 2025,
          notes: c.notes,
        },
        update: {},  // Don't overwrite edits
      })
    )
  );

  revalidatePath("/admin");
}

export async function updateCostRegistry(id: string, unitCost: number, notes?: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  await prisma.costRegistry.update({
    where: { id },
    data: { unitCost, notes },
  });
  revalidatePath("/admin");
}

export async function resetCostRegistry(id: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const entry = await prisma.costRegistry.findUnique({ where: { id } });
  if (!entry) return;

  const defaults = getDefaultsForCity(entry.city);
  const def = defaults.find(c => c.itemKey === entry.itemKey);
  if (!def) return;

  await prisma.costRegistry.update({
    where: { id },
    data: { unitCost: def.unitCost, notes: def.notes },
  });
  revalidatePath("/admin");
}

// ─── Line template actions ────────────────────────────────────────────────────

export type LineTemplateFields = {
  domain?: BudgetDomain | null;
  section: BudgetSection;
  description: string;
  costCategory: InflationType;
  unitType: string;
  notes?: string | null;
  salaryHint?: string | null;
  isAutoGenerated?: boolean;
  inputVar: string;
  inputMonthly?: boolean;
  supervisorRatioKey?: string | null;
  isSalaryStub?: boolean;
  userInputCost?: string | null;
  costKey?: string | null;
  costKey2?: string | null;
  costKey3?: string | null;
  costMonthly?: boolean;
  workerRatioKey?: string | null;
  bufferKey?: string | null;
  costPctOf?: string | null;
  costPct?: number | null;
  y1UnitsZero?: boolean;
};

export async function toggleLineTemplate(id: string, isActive: boolean) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");
  await prisma.lineTemplate.update({ where: { id }, data: { isActive } });
  revalidatePath("/admin");
}

export async function addLineTemplate(city: string, fields: LineTemplateFields) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const maxPos = await prisma.lineTemplate.aggregate({
    where: { city },
    _max: { position: true },
  });
  const position = (maxPos._max.position ?? 0) + 1;
  const templateKey = `custom.${Date.now()}`;

  await prisma.lineTemplate.create({
    data: { city, templateKey, position, isActive: true, ...fields },
  });
  revalidatePath("/admin");
}

export async function updateLineTemplate(id: string, fields: Partial<LineTemplateFields>) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");
  await prisma.lineTemplate.update({ where: { id }, data: fields });
  revalidatePath("/admin");
}

export async function deleteLineTemplate(id: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");
  await prisma.lineTemplate.delete({ where: { id } });
  revalidatePath("/admin");
}

export async function reorderLineTemplates(city: string, orderedIds: string[]) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");
  await prisma.$transaction(
    orderedIds.map((id, position) => prisma.lineTemplate.update({ where: { id }, data: { position } }))
  );
  revalidatePath("/admin");
}
