import type { BudgetSection, InflationType, LineTemplate } from "@/app/generated/prisma/client";
import { lookupCost } from "@/lib/budget-costs";

export type BudgetGeneratorInputs = Record<string, number>;

export type GeneratedLine = {
  domain: string | null;
  section: BudgetSection;
  position: number;
  description: string;
  costCategory: InflationType;
  unitType: string;
  isAutoGenerated: boolean;
  inputVar: string;
  salaryHint?: string | null;
  notes?: string | null;
  y1Units: number; y1UnitCost: number; y1AllocPct: number; y1Total: number;
  y2Units: number; y2UnitCost: number; y2AllocPct: number; y2Total: number;
  y3Units: number; y3UnitCost: number; y3AllocPct: number; y3Total: number;
};

const INFLATION: Record<InflationType, number> = { Salary: 0.10, Other: 0.05, Nil: 0.00 };

function resolveInputVar(v: string, inp: BudgetGeneratorInputs): number {
  if (v === "fixed_1")  return 1;
  if (v === "fixed_12") return 12;
  if (v === "cosTotal") return (inp.nClusters ?? 0) * (inp.cosPerCluster ?? 0);
  // gate:VAR → 1 if VAR > 0, else 0. Use with inputMonthly + inputThreshold=0 for
  // "1 person × 12 months, but only when VAR > 0"
  if (v.startsWith("gate:")) return (inp[v.slice(5)] ?? 0) > 0 ? 1 : 0;
  return inp[v] ?? 0;
}

function resolveUserInput(field: string, inp: BudgetGeneratorInputs): number {
  return inp[field] ?? 0;
}

function computeUnitCount(t: LineTemplate, inp: BudgetGeneratorInputs, reg: Record<string, number>): number {
  const base = resolveInputVar(t.inputVar, inp);
  if (t.inputThreshold != null && base <= t.inputThreshold) return 0;
  if (t.supervisorRatioKey) {
    const ratio = lookupCost(reg, t.supervisorRatioKey);
    return ratio > 0 ? Math.ceil(base / ratio) * 12 : 0;
  }
  return t.inputMonthly ? base * 12 : base;
}

function computeUnitCost(t: LineTemplate, inp: BudgetGeneratorInputs, reg: Record<string, number>): number {
  if (t.isSalaryStub) return 0;

  if (t.userInputCost) return resolveUserInput(t.userInputCost, inp);

  if (t.costPctOf && t.costPct != null) {
    return Math.round(lookupCost(reg, t.costPctOf) * t.costPct / 100);
  }

  if (t.workerRatioKey && t.costKey) {
    const ratio   = lookupCost(reg, t.workerRatioKey);
    const salary  = lookupCost(reg, t.costKey);
    const buffer  = t.bufferKey ? lookupCost(reg, t.bufferKey) : 0;
    return Math.round(ratio * salary * 12 * (1 + buffer / 100));
  }

  if (!t.costKey) return 0;

  let cost = lookupCost(reg, t.costKey);
  if (t.costKey2) cost *= lookupCost(reg, t.costKey2);
  if (t.costKey3) cost *= lookupCost(reg, t.costKey3);
  if (t.costMonthly) cost *= 12;

  return Math.round(cost);
}

function templateToLine(
  t: LineTemplate,
  inp: BudgetGeneratorInputs,
  reg: Record<string, number>,
  position: number,
  years: number,
): GeneratedLine {
  const fullUnits  = computeUnitCount(t, inp, reg);
  const unitCost   = computeUnitCost(t, inp, reg);
  const alloc      = 1;
  const rate       = INFLATION[t.costCategory];
  const y2UnitCost = unitCost * (1 + rate);
  const y3UnitCost = y2UnitCost * (1 + rate);

  const applyY1 = t.applyY1 ?? true;
  const applyY2 = (t.applyY2 ?? true) && years >= 3;
  const applyY3 = (t.applyY3 ?? true) && years >= 3;

  const y1Units = applyY1 ? (t.y1UnitsZero ? 0 : fullUnits) : 0;
  const y2Units = applyY2 ? (t.y2UnitsScale != null ? Math.round(fullUnits * t.y2UnitsScale) : fullUnits) : 0;
  const y3Units = applyY3 ? (t.y3UnitsScale != null ? Math.round(fullUnits * t.y3UnitsScale) : fullUnits) : 0;

  return {
    domain:          t.domain,
    section:         t.section,
    position,
    description:     t.description,
    costCategory:    t.costCategory,
    unitType:        t.unitType,
    isAutoGenerated: t.isAutoGenerated,
    inputVar:        t.inputVar,
    salaryHint:      t.salaryHint,
    notes:           t.notes,
    y1Units, y1UnitCost: unitCost,   y1AllocPct: alloc, y1Total: Math.round(y1Units * unitCost * alloc),
    y2Units, y2UnitCost: applyY2 ? y2UnitCost : 0, y2AllocPct: alloc, y2Total: Math.round(y2Units * y2UnitCost * alloc),
    y3Units, y3UnitCost: applyY3 ? y3UnitCost : 0, y3AllocPct: alloc, y3Total: Math.round(y3Units * y3UnitCost * alloc),
  };
}

// Injects all programme inputs into registry under inp.* namespace
export function buildAugmentedRegistry(
  registry: Record<string, number>,
  inp: BudgetGeneratorInputs,
): Record<string, number> {
  return {
    ...registry,
    ...Object.fromEntries(Object.entries(inp).map(([k, v]) => [`inp.${k}`, v])),
    "inp.cosTotal": (inp.nClusters ?? 0) * (inp.cosPerCluster ?? 0),
  };
}

export function generateBudgetLines(
  domains: string[],
  inp: BudgetGeneratorInputs,
  years: number,
  registry: Record<string, number>,
  templates: LineTemplate[],
): GeneratedLine[] {
  const augmented = buildAugmentedRegistry(registry, inp);
  const active = templates
    .filter(t => t.isActive)
    .filter(t => t.domain === null || domains.includes(t.domain))
    .sort((a, b) => a.position - b.position);

  return active.map((t, i) => templateToLine(t, inp, augmented, i, years));
}
