import type { BudgetSection, BudgetLineCadence, InflationType, LineTemplate } from "@/app/generated/prisma/client";
import { lookupCost } from "@/lib/budget-costs";

export type BudgetGeneratorInputs = Record<string, number>;

export type GeneratedLine = {
  domain: string | null;
  section: BudgetSection;
  position: number;
  description: string;
  costCategory: InflationType;
  unitType: string;
  isAutoGenerated: boolean;
  inputVar: string;
  salaryHint?: string | null;
  notes?: string | null;
  templateKey: string;
  cadence: BudgetLineCadence;
  plannedMonths: number[];
  y1Units: number; y1UnitCost: number; y1AllocPct: number; y1Total: number;
  y2Units: number; y2UnitCost: number; y2AllocPct: number; y2Total: number;
  y3Units: number; y3UnitCost: number; y3AllocPct: number; y3Total: number;
  y4Units: number; y4UnitCost: number; y4AllocPct: number; y4Total: number;
  y5Units: number; y5UnitCost: number; y5AllocPct: number; y5Total: number;
};

/** Inflation rates as decimal fractions per InflationType. */
export type InflationRates = Record<InflationType, number>;

/** Defaults track the previously hard-coded values. */
export const DEFAULT_INFLATION_RATES: InflationRates = { Salary: 0.10, Other: 0.05, Nil: 0.00 };

/** Position of the pro-rated stub when the horizon isn't a whole number of years. */
export type PartialPosition = "start" | "end";

export type GeneratorOpts = {
  /** Total horizon in months. 1..60. */
  horizonMonths: number;
  /** When false, every year-band uses the Y1 unit cost (no compounding). */
  applyInflation: boolean;
  /** Per-budget rates; falls back to DEFAULT_INFLATION_RATES. */
  inflationRates?: InflationRates;
  /** Where the partial year sits: "end" (default) or "start" (Year 1 partial). */
  partialPosition?: PartialPosition;
};

/** Fraction of a full year covered by year-band k (1-indexed). 0 outside horizon.
 *  When partialPosition is "start" and the horizon has a stub, Year 1 is the
 *  partial band and the remaining bands are full; otherwise the stub is last. */
export function yearFactor(k: number, horizonMonths: number, partialPosition: PartialPosition = "end"): number {
  if (k < 1 || k > 5) return 0;
  const fullYears = Math.floor(horizonMonths / 12);
  const tailMonths = horizonMonths - fullYears * 12;
  if (tailMonths === 0) return k <= fullYears ? 1 : 0;
  if (partialPosition === "start") {
    if (k === 1) return tailMonths / 12;
    if (k <= fullYears + 1) return 1;
    return 0;
  }
  // "end" (default): full years first, partial stub last.
  if (k <= fullYears) return 1;
  if (k === fullYears + 1) return tailMonths / 12;
  return 0;
}

/** Number of active year-bands for this horizon (1..5). */
export function activeYearBands(horizonMonths: number): number {
  return Math.min(5, Math.ceil(Math.max(1, horizonMonths) / 12));
}

function resolveInputVar(v: string, inp: BudgetGeneratorInputs): number {
  if (v === "fixed_1")  return 1;
  if (v === "fixed_12") return 12;
  if (v === "cosTotal") return (inp.nClusters ?? 0) * (inp.cosPerCluster ?? 0);
  // gate:VAR → 1 if VAR > 0, else 0. Use with inputMonthly + inputThreshold=0 for
  // "1 person × 12 months, but only when VAR > 0"
  if (v.startsWith("gate:")) return (inp[v.slice(5)] ?? 0) > 0 ? 1 : 0;
  return inp[v] ?? 0;
}

function resolveUserInput(field: string, inp: BudgetGeneratorInputs): number {
  return inp[field] ?? 0;
}

function computeUnitCount(t: LineTemplate, inp: BudgetGeneratorInputs, reg: Record<string, number>): number {
  const base = resolveInputVar(t.inputVar, inp);
  if (t.inputThreshold != null && base <= t.inputThreshold) return 0;
  if (t.supervisorRatioKey) {
    const ratio = lookupCost(reg, t.supervisorRatioKey);
    return ratio > 0 ? Math.ceil(base / ratio) * 12 : 0;
  }
  return t.inputMonthly ? base * 12 : base;
}

function computeUnitCost(t: LineTemplate, inp: BudgetGeneratorInputs, reg: Record<string, number>): number {
  if (t.isSalaryStub) return 0;

  if (t.userInputCost) return resolveUserInput(t.userInputCost, inp);

  if (t.costPctOf && t.costPct != null) {
    return Math.round(lookupCost(reg, t.costPctOf) * t.costPct / 100);
  }

  if (t.workerRatioKey && t.costKey) {
    const ratio   = lookupCost(reg, t.workerRatioKey);
    const salary  = lookupCost(reg, t.costKey);
    const buffer  = t.bufferKey ? lookupCost(reg, t.bufferKey) : 0;
    return Math.round(ratio * salary * 12 * (1 + buffer / 100));
  }

  if (!t.costKey) return 0;

  let cost = lookupCost(reg, t.costKey);
  if (t.costKey2) cost *= lookupCost(reg, t.costKey2);
  if (t.costKey3) cost *= lookupCost(reg, t.costKey3);
  if (t.costMonthly) cost *= 12;

  return Math.round(cost);
}

/** Per-template applyYk for k=1..3 (legacy fields); Y4/Y5 default to true. */
function templateAppliesToYear(t: LineTemplate, k: number): boolean {
  if (k === 1) return t.applyY1 ?? true;
  if (k === 2) return t.applyY2 ?? true;
  if (k === 3) return t.applyY3 ?? true;
  // No applyY4 / applyY5 fields: extend the Y3 flag to later years so recurring
  // lines carry forward but a Y1-only line (one-time capex, applyY3=false) does
  // NOT reappear in Y4/Y5 on long (48–60mo) horizons.
  return t.applyY3 ?? true;
}

/** Per-template unit scaling for k=2..3; k=1, 4, 5 always use the full unit count. */
function templateUnitScale(t: LineTemplate, k: number): number {
  if (k === 2 && t.y2UnitsScale != null) return t.y2UnitsScale;
  if (k === 3 && t.y3UnitsScale != null) return t.y3UnitsScale;
  return 1;
}

function templateToLine(
  t: LineTemplate,
  inp: BudgetGeneratorInputs,
  reg: Record<string, number>,
  position: number,
  opts: GeneratorOpts,
): GeneratedLine {
  const fullUnits   = computeUnitCount(t, inp, reg);
  const unitCost    = computeUnitCost(t, inp, reg);
  const allocPct    = 1;
  const rates       = opts.inflationRates ?? DEFAULT_INFLATION_RATES;
  const rate        = opts.applyInflation ? rates[t.costCategory] : 0;
  const horizon     = opts.horizonMonths;
  const partialPos  = opts.partialPosition ?? "end";

  const computeYear = (k: number): { units: number; unitCost: number; allocPct: number; total: number } => {
    const factor = yearFactor(k, horizon, partialPos);
    if (factor === 0 || !templateAppliesToYear(t, k)) {
      return { units: 0, unitCost: 0, allocPct, total: 0 };
    }
    // Y1: y1UnitsZero override forces 0 units (e.g. CAPEX maintenance starting Y2).
    if (k === 1 && t.y1UnitsZero) {
      return { units: 0, unitCost, allocPct, total: 0 };
    }
    const scale     = templateUnitScale(t, k);
    const proRated  = factor === 1 ? scale : scale * factor;
    const rawUnits  = fullUnits * proRated;
    // Round Y2/Y3 units when an explicit integer scale was set, otherwise keep float.
    const units     = (k === 2 || k === 3) && (k === 2 ? t.y2UnitsScale != null : t.y3UnitsScale != null)
      ? Math.round(rawUnits)
      : rawUnits;
    const yearCost  = unitCost * Math.pow(1 + rate, k - 1);
    return {
      units,
      unitCost: yearCost,
      allocPct,
      total: Math.round(units * yearCost * allocPct),
    };
  };

  const y1 = computeYear(1);
  const y2 = computeYear(2);
  const y3 = computeYear(3);
  const y4 = computeYear(4);
  const y5 = computeYear(5);

  // Capex is the one section where a default non-monthly cadence is safe:
  // by convention these are paid upfront. All other sections default to
  // monthly straight-line and rely on the partner to mark camps / TLM / etc.
  // as one_time or seasonal in the editor.
  const isCapex = t.section === "capex";
  const cadence: BudgetLineCadence = isCapex ? "one_time" : "monthly";
  const plannedMonths: number[]    = isCapex ? [1] : [];

  return {
    domain:          t.domain,
    section:         t.section,
    position,
    description:     t.description,
    costCategory:    t.costCategory,
    unitType:        t.unitType,
    isAutoGenerated: t.isAutoGenerated,
    inputVar:        t.inputVar,
    salaryHint:      t.salaryHint,
    notes:           t.notes,
    templateKey:     t.templateKey,
    cadence,
    plannedMonths,
    y1Units: y1.units, y1UnitCost: y1.unitCost, y1AllocPct: y1.allocPct, y1Total: y1.total,
    y2Units: y2.units, y2UnitCost: y2.unitCost, y2AllocPct: y2.allocPct, y2Total: y2.total,
    y3Units: y3.units, y3UnitCost: y3.unitCost, y3AllocPct: y3.allocPct, y3Total: y3.total,
    y4Units: y4.units, y4UnitCost: y4.unitCost, y4AllocPct: y4.allocPct, y4Total: y4.total,
    y5Units: y5.units, y5UnitCost: y5.unitCost, y5AllocPct: y5.allocPct, y5Total: y5.total,
  };
}

// Injects all programme inputs into registry under inp.* namespace
export function buildAugmentedRegistry(
  registry: Record<string, number>,
  inp: BudgetGeneratorInputs,
): Record<string, number> {
  return {
    ...registry,
    ...Object.fromEntries(Object.entries(inp).map(([k, v]) => [`inp.${k}`, v])),
    "inp.cosTotal": (inp.nClusters ?? 0) * (inp.cosPerCluster ?? 0),
  };
}

export function generateBudgetLines(
  domains: string[],
  inp: BudgetGeneratorInputs,
  opts: GeneratorOpts,
  registry: Record<string, number>,
  templates: LineTemplate[],
): GeneratedLine[] {
  const augmented = buildAugmentedRegistry(registry, inp);
  const active = templates
    .filter(t => t.isActive)
    .filter(t => t.domain === null || domains.includes(t.domain))
    .sort((a, b) => a.position - b.position);

  return active.map((t, i) => templateToLine(t, inp, augmented, i, opts));
}
