export type TemplateSpec = {
  templateKey: string;
  domain?: string | null;
  section: string;
  description: string;
  costCategory: string;
  unitType: string;
  notes?: string;
  salaryHint?: string;
  isAutoGenerated?: boolean;
  inputVar?: string;
  inputMonthly?: boolean;
  supervisorRatioKey?: string;
  inputThreshold?: number;
  isSalaryStub?: boolean;
  userInputCost?: string;
  costKey?: string;
  costKey2?: string;
  costKey3?: string;
  costMonthly?: boolean;
  workerRatioKey?: string;
  bufferKey?: string;
  costPctOf?: string;
  costPct?: number;
  y1UnitsZero?: boolean;
};

const CHILDREN: TemplateSpec[] = [
  { templateKey: "children.lead",       section: "salary",    description: "Children Programme Lead",                                  costCategory: "Salary", unitType: "Month",   inputVar: "fixed_12",   isSalaryStub: true,  salaryHint: "₹40,000–55,000/month" },
  { templateKey: "children.cf",         section: "salary",    description: "Community Facilitator – Children",                         costCategory: "Salary", unitType: "Month",   inputVar: "nCLCs",      inputMonthly: true,  isSalaryStub: true, salaryHint: "₹21,000–27,000/month per CF" },
  { templateKey: "children.clc_setup",  section: "capex",     description: "CLC setup / painting & civil works (one-time)",            costCategory: "Nil",    unitType: "Per CLC", inputVar: "nCLCs",      costKey: "children.clc_setup_cost" },
  { templateKey: "children.exposure",   section: "travel",    description: "Staff exposure visits",                                    costCategory: "Other",  unitType: "Annual",  inputVar: "nCLCs",      costKey: "children.staff_exposure_visit_cost" },
  { templateKey: "children.snacks",     section: "programme", description: "Snacks for children",                                      costCategory: "Other",  unitType: "Per CLC", inputVar: "nCLCs",      costKey: "children.snack_per_child_per_day",       costKey2: "children.snack_days_per_year",          costKey3: "children.children_per_clc" },
  { templateKey: "children.leisure",    section: "programme", description: "Leisure class materials",                                  costCategory: "Other",  unitType: "Per CLC", inputVar: "nCLCs",      costKey: "children.leisure_material_per_day",      costKey2: "children.leisure_days_per_year",        costKey3: "children.children_per_clc" },
  { templateKey: "children.parents",    section: "programme", description: "Parent interaction sessions",                              costCategory: "Other",  unitType: "Per CLC", inputVar: "nCLCs",      costKey: "children.parent_session_per_person",     costKey2: "children.parent_sessions_per_year",     costKey3: "children.parents_per_centre" },
  { templateKey: "children.social",     section: "programme", description: "Social awareness events",                                  costCategory: "Other",  unitType: "Per CLC", inputVar: "nCLCs",      costKey: "children.social_awareness_per_event",    costKey2: "children.social_awareness_events" },
  { templateKey: "children.visits",     section: "programme", description: "Exposure visit for children",                              costCategory: "Other",  unitType: "Per CLC", inputVar: "nCLCs",      costKey: "children.exposure_visit_per_child",      costKey2: "children.exposure_children" },
  { templateKey: "children.camps",      section: "programme", description: "Summer / Dasara camps",                                    costCategory: "Other",  unitType: "Per CLC", inputVar: "nCLCs",      costKey: "children.camp_cost",                     costKey2: "children.camps_per_year" },
  { templateKey: "children.leadership", section: "programme", description: "Leadership training",                                      costCategory: "Other",  unitType: "Per CLC", inputVar: "nCLCs",      costKey: "children.leadership_training_cost" },
  { templateKey: "children.edu",        section: "programme", description: "Educational materials / TLM",                              costCategory: "Other",  unitType: "Per CLC", inputVar: "nCLCs",      costKey: "children.education_materials_cost" },
  { templateKey: "children.profiling",  section: "programme", description: "Child profiling & external training",                      costCategory: "Other",  unitType: "Per CLC", inputVar: "nCLCs",      costKey: "children.profiling_external_training" },
  { templateKey: "children.rent",       section: "programme", description: "CLC rent & maintenance",                                   costCategory: "Other",  unitType: "Month",   inputVar: "nCLCs",      inputMonthly: true,  userInputCost: "clcRentPerMonth" },
];

const YOUTH: TemplateSpec[] = [
  { templateKey: "youth.lead",          section: "salary",    description: "Youth Programme Lead",                                     costCategory: "Salary", unitType: "Month",    inputVar: "fixed_12",   isSalaryStub: true,  salaryHint: "₹41,000–48,000/month" },
  { templateKey: "youth.yrc_coord",     section: "salary",    description: "Youth Resource Centre Coordinator",                        costCategory: "Salary", unitType: "Month",    inputVar: "nYRCs",      inputMonthly: true,  isSalaryStub: true, salaryHint: "₹27,000–37,000/month per YRC" },
  { templateKey: "youth.cf",            section: "salary",    description: "Community Facilitator – Youth",                            costCategory: "Salary", unitType: "Month",    inputVar: "nYRCs",      inputMonthly: true,  isSalaryStub: true, salaryHint: "₹18,000–26,000/month per CF" },
  { templateKey: "youth.exposure",      section: "travel",    description: "Staff exposure visits",                                    costCategory: "Other",  unitType: "Annual",   inputVar: "nYRCs",      costKey: "youth.staff_exposure_visit_cost" },
  { templateKey: "youth.small_group",   section: "programme", description: "Small group meetings in area",                             costCategory: "Other",  unitType: "Month",    inputVar: "nYRCs",      inputMonthly: true,  costKey: "youth.small_group_meeting_per_month" },
  { templateKey: "youth.yuva_adda",     section: "programme", description: "Workshops – Yuva Adda",                                   costCategory: "Other",  unitType: "Per YRC",  inputVar: "nYRCs",      costKey: "youth.yuva_adda_cost_per_workshop",      costKey2: "youth.yuva_adda_workshops_per_year" },
  { templateKey: "youth.leadership",    section: "programme", description: "Leadership development training",                          costCategory: "Other",  unitType: "Per YRC",  inputVar: "nYRCs",      costKey: "youth.leadership_training_cost",         costKey2: "youth.leadership_trainings_per_year" },
  { templateKey: "youth.felicitation",  section: "programme", description: "Felicitation of youth",                                   costCategory: "Other",  unitType: "Per YRC",  inputVar: "nYRCs",      costKey: "youth.felicitation_cost",                costKey2: "youth.felicitations_per_year" },
  { templateKey: "youth.sports",        section: "programme", description: "Sports event",                                             costCategory: "Other",  unitType: "Per YRC",  inputVar: "nYRCs",      costKey: "youth.sports_event_cost",                costKey2: "youth.sports_events_per_year" },
  { templateKey: "youth.festival",      section: "programme", description: "Youth Festival (1/year)",                                  costCategory: "Other",  unitType: "Per YRC",  inputVar: "nYRCs",      costKey: "youth.youth_festival_cost" },
  { templateKey: "youth.comm_exposure", section: "programme", description: "Exposure visits for community youth",                      costCategory: "Other",  unitType: "Per YRC",  inputVar: "nYRCs",      costKey: "youth.community_exposure_cost" },
  { templateKey: "youth.social",        section: "programme", description: "Youth-led social actions",                                 costCategory: "Other",  unitType: "Per YRC",  inputVar: "nYRCs",      costKey: "youth.social_actions_per_yrc" },
  { templateKey: "youth.stationery",    section: "programme", description: "Stationery, IEC, photocopy & printing",                    costCategory: "Other",  unitType: "Per YRC",  inputVar: "nYRCs",      costKey: "youth.stationery_per_yrc" },
  { templateKey: "youth.rent",          section: "programme", description: "YRC rent & maintenance",                                   costCategory: "Other",  unitType: "Month",    inputVar: "nYRCs",      inputMonthly: true,  userInputCost: "yrcRentPerMonth" },
];

const ELDERLY: TemplateSpec[] = [
  { templateKey: "elderly.incharge",    section: "salary",    description: "Elderly Resource Centre In-charge",                        costCategory: "Salary", unitType: "Month",      inputVar: "nElderlyCentres", inputMonthly: true,  isSalaryStub: true,  salaryHint: "₹22,000–28,000/month per centre" },
  { templateKey: "elderly.co",          section: "salary",    description: "Community Organisers – Elderly",                           costCategory: "Salary", unitType: "Month",      inputVar: "nElderlyCentres", inputMonthly: true,  isSalaryStub: true,  salaryHint: "₹21,000–22,000/month per CO" },
  { templateKey: "elderly.kitchen",     section: "salary",    description: "Community Kitchen In-charge",                              costCategory: "Salary", unitType: "Month",      inputVar: "nElderlyCentres", inputMonthly: true,  isSalaryStub: true,  salaryHint: "₹25,000/month per centre" },
  { templateKey: "elderly.setup",       section: "capex",     description: "Elderly centre setup (beds, utensils, linen)",             costCategory: "Nil",    unitType: "Per centre", inputVar: "nElderlyCentres", costKey: "elderly.centre_setup_cost" },
  { templateKey: "elderly.travel",      section: "travel",    description: "Kitchen in-charge local travel",                           costCategory: "Other",  unitType: "Month",      inputVar: "nElderlyCentres", inputMonthly: true,  costKey: "elderly.kitchen_incharge_travel" },
  { templateKey: "elderly.nutrition",   section: "programme", description: "Day care nutrition (breakfast + lunch + snack)",           costCategory: "Other",  unitType: "Month",      inputVar: "nElderly",        inputMonthly: true,  costKey: "elderly.nutrition_per_person_per_day", costKey2: "elderly.nutrition_days_per_month" },
  { templateKey: "elderly.dry_ration",  section: "programme", description: "Dry ration",                                              costCategory: "Other",  unitType: "Month",      inputVar: "nElderly",        inputMonthly: true,  costKey: "elderly.dry_ration_per_person_per_month" },
  { templateKey: "elderly.vegetables",  section: "programme", description: "Vegetables",                                              costCategory: "Other",  unitType: "Month",      inputVar: "nElderly",        inputMonthly: true,  costKey: "elderly.vegetable_per_person_per_month" },
  { templateKey: "elderly.gas",         section: "programme", description: "Gas refill",                                              costCategory: "Other",  unitType: "Per centre", inputVar: "nElderlyCentres", costKey: "elderly.gas_refill_cost",                costKey2: "elderly.gas_refills_per_year" },
  { templateKey: "elderly.meeting",     section: "programme", description: "Monthly meeting – refreshments",                          costCategory: "Other",  unitType: "Per centre", inputVar: "nElderlyCentres", costKey: "elderly.meeting_refreshment_per_person", costKey2: "elderly.elderly_per_meeting",           costMonthly: true },
  { templateKey: "elderly.annual_day",  section: "programme", description: "Annual day – Senior Citizen Day",                         costCategory: "Other",  unitType: "Per centre", inputVar: "nElderlyCentres", costKey: "elderly.annual_day_cost",                costKey2: "elderly.annual_days_per_year" },
  { templateKey: "elderly.volunteers",  section: "programme", description: "Community volunteers honoraria",                          costCategory: "Other",  unitType: "Month",      inputVar: "nElderlyCentres", inputMonthly: true,  costKey: "elderly.volunteer_honorarium_per_month", costKey2: "elderly.volunteers_per_centre" },
  { templateKey: "elderly.misc",        section: "programme", description: "Miscellaneous & contingency",                             costCategory: "Other",  unitType: "Per centre", inputVar: "nElderlyCentres", costKey: "elderly.misc_contingency_per_centre" },
  { templateKey: "elderly.rent",        section: "programme", description: "Centre rent & maintenance",                               costCategory: "Other",  unitType: "Month",      inputVar: "nElderlyCentres", inputMonthly: true,  userInputCost: "elderlyCentreRentPerMonth" },
];

const WR: TemplateSpec[] = [
  { templateKey: "wr.lead",            section: "salary",    description: "Entitlement & Collectivization Lead",                       costCategory: "Salary", unitType: "Month",          inputVar: "fixed_12",      isSalaryStub: true,  salaryHint: "₹40,000–52,000/month" },
  { templateKey: "wr.cos",             section: "salary",    description: "Community Organisers – E&C",                               costCategory: "Salary", unitType: "Month",          inputVar: "cosTotal",      inputMonthly: true,  isSalaryStub: true,  salaryHint: "₹21,000–26,000/month per CO" },
  { templateKey: "wr.dept_travel",     section: "travel",    description: "Interaction with departments (travel)",                    costCategory: "Other",  unitType: "Annual",         inputVar: "nClusters",     costKey: "wr.dept_interaction_per_cluster" },
  { templateKey: "wr.slum_meeting",    section: "programme", description: "Slum-level monthly meeting",                              costCategory: "Other",  unitType: "Per settlement", inputVar: "nSettlements",  costKey: "wr.slum_meeting_refreshment",        costKey2: "wr.slum_meeting_participants",     costMonthly: true },
  { templateKey: "wr.cluster_meeting", section: "programme", description: "Cluster-level monthly meeting",                           costCategory: "Other",  unitType: "Per cluster",    inputVar: "nClusters",     costKey: "wr.cluster_meeting_refreshment",     costKey2: "wr.cluster_meeting_participants",  costMonthly: true },
  { templateKey: "wr.city_training",   section: "programme", description: "City-level training of community groups",                  costCategory: "Other",  unitType: "Annual",         inputVar: "fixed_1",       costKey: "wr.city_training_cost" },
  { templateKey: "wr.city_meeting",    section: "programme", description: "City-level meetings of community groups",                  costCategory: "Other",  unitType: "Annual",         inputVar: "fixed_1",       costKey: "wr.city_meeting_cost" },
  { templateKey: "wr.exposure",        section: "programme", description: "Exposure visit of community groups",                      costCategory: "Other",  unitType: "Per cluster",    inputVar: "nClusters",     costKey: "wr.community_exposure_per_leader",   costKey2: "wr.leaders_per_cluster" },
  { templateKey: "wr.entitlement",     section: "programme", description: "Improving access to entitlements / camps",                costCategory: "Other",  unitType: "Per settlement", inputVar: "nSettlements",  costKey: "wr.entitlement_camp_per_settlement" },
  { templateKey: "wr.consultation",    section: "programme", description: "Consultation on issues (venue + food)",                   costCategory: "Other",  unitType: "Annual",         inputVar: "fixed_1",       costKey: "wr.consultation_cost" },
  { templateKey: "wr.governance",      section: "programme", description: "Strengthening of governance / MAS / JRS engagement",      costCategory: "Other",  unitType: "Annual",         inputVar: "nClusters",     costKey: "wr.governance_cost_per_cluster" },
  { templateKey: "wr.occasions",       section: "programme", description: "Observation of special occasions",                        costCategory: "Other",  unitType: "Annual",         inputVar: "fixed_1",       costKey: "wr.special_occasions_cost" },
  { templateKey: "wr.civic_baseline",  section: "programme", description: "Civic community baseline",                                costCategory: "Other",  unitType: "Annual",         inputVar: "fixed_1",       costKey: "wr.civic_baseline_cost" },
  { templateKey: "wr.rc_rent",         section: "programme", description: "Resource Centre rent & maintenance",                      costCategory: "Other",  unitType: "Month",          inputVar: "fixed_12",      userInputCost: "rcRentPerMonth" },
];

function crecheTemplates(city: string): TemplateSpec[] {
  const base: TemplateSpec[] = [
    { templateKey: "creche.supervisor",        section: "salary",    description: "Creche Supervisor",                                             costCategory: "Salary", unitType: "Month",      inputVar: "nCreches", supervisorRatioKey: "creche.supervisor_per_n_creches",   costKey: "creche.supervisor_salary_per_month" },
    { templateKey: "creche.coordinator",       section: "salary",    description: "Cluster Coordinator",                                           costCategory: "Salary", unitType: "Month",      inputVar: "nCreches", supervisorRatioKey: "creche.coordinator_per_n_creches",  costKey: "creche.coordinator_salary_per_month" },
    { templateKey: "creche.setup",             section: "capex",     description: "One-time creche setup (equipment, utensils, linen, safety)",    costCategory: "Nil",    unitType: "Per creche", inputVar: "nCreches",  costKey: "creche.setup_cost" },
    { templateKey: "creche.capex_maint",       section: "capex",     description: "CAPEX maintenance from year 2 (5% of setup cost)",              costCategory: "Nil",    unitType: "Per creche", inputVar: "nCreches",  costPctOf: "creche.setup_cost", costPct: 5, y1UnitsZero: true },
    { templateKey: "creche.supervisor_travel", section: "travel",    description: "Creche supervisor travel",                                      costCategory: "Other",  unitType: "Month",      inputVar: "nCreches", supervisorRatioKey: "creche.supervisor_per_n_creches",   costKey: "creche.supervisor_travel_per_month" },
    { templateKey: "creche.coord_travel",      section: "travel",    description: "Cluster coordinator travel",                                    costCategory: "Other",  unitType: "Month",      inputVar: "nCreches", supervisorRatioKey: "creche.coordinator_per_n_creches",  costKey: "creche.coordinator_travel_per_month" },
    { templateKey: "creche.worker_hon",        section: "programme", description: "Creche worker honorarium",                                      costCategory: "Salary", unitType: "Per creche", inputVar: "nCreches",  workerRatioKey: "creche.workers_per_creche", costKey: "creche.worker_honorarium_per_month", bufferKey: "creche.maternity_buffer_pct" },
    { templateKey: "creche.feeding",           section: "programme", description: "Feeding cost – breakfast + lunch + evening snacks",             costCategory: "Other",  unitType: "Per creche", inputVar: "nCreches",  costKey: "creche.feeding_cost_per_child_per_year" },
    { templateKey: "creche.eggs",              section: "programme", description: "Eggs",                                                          costCategory: "Other",  unitType: "Per creche", inputVar: "nCreches",  costKey: "creche.egg_cost_per_year" },
    { templateKey: "creche.gas",               section: "programme", description: "Gas / fuel",                                                    costCategory: "Other",  unitType: "Per creche", inputVar: "nCreches",  costKey: "creche.gas_cost_per_year" },
    { templateKey: "creche.hygiene",           section: "programme", description: "Hygiene, sanitation, first aid & stationery",                   costCategory: "Other",  unitType: "Per creche", inputVar: "nCreches",  costKey: "creche.hygiene_cost_per_year" },
    { templateKey: "creche.transport",         section: "programme", description: "Food transport",                                                costCategory: "Other",  unitType: "Per creche", inputVar: "nCreches",  costKey: "creche.food_transport_per_year" },
    { templateKey: "creche.play",              section: "programme", description: "Play materials, nappies & spare clothes",                       costCategory: "Other",  unitType: "Per creche", inputVar: "nCreches",  costKey: "creche.play_materials_per_year" },
    { templateKey: "creche.flexi",             section: "programme", description: "Flexi fund for miscellaneous expenses",                         costCategory: "Other",  unitType: "Per creche", inputVar: "nCreches",  costKey: "creche.flexi_fund_per_year" },
    { templateKey: "creche.training",          section: "programme", description: "Training & review meetings of creche workers",                  costCategory: "Other",  unitType: "Per creche", inputVar: "nCreches",  costKey: "creche.training_cost_per_year" },
    { templateKey: "creche.cg_food",           section: "programme", description: "Food for caregivers",                                           costCategory: "Other",  unitType: "Per creche", inputVar: "nCreches",  costKey: "creche.caregiver_food_per_year" },
    { templateKey: "creche.insurance",         section: "programme", description: "Health & accident insurance",                                   costCategory: "Other",  unitType: "Per creche", inputVar: "nCreches",  costKey: "creche.insurance_per_creche_per_year" },
    { templateKey: "creche.rent",              section: "programme", description: "Creche rent",                                                   costCategory: "Other",  unitType: "Month",      inputVar: "nCreches",  inputMonthly: true, userInputCost: "crecheRentPerMonth" },
  ];

  if (city === "Chennai") {
    base.splice(2, 0,
      { templateKey: "creche.al_manager",        section: "salary", description: "Accounts & Logistics Manager",             costCategory: "Salary", unitType: "Month", inputVar: "fixed_12", costKey: "creche.accounts_manager_salary_per_month" },
    );
    base.splice(7, 0,
      { templateKey: "creche.al_manager_travel",  section: "travel", description: "Accounts & Logistics Manager travel",      costCategory: "Other",  unitType: "Month", inputVar: "fixed_12", costKey: "creche.accounts_manager_travel_per_month" },
    );
  }

  return base;
}

const CROSS: TemplateSpec[] = [
  { templateKey: "cross.mis",           section: "salary",    description: "MIS Coordinator",                            costCategory: "Salary", unitType: "Month",  inputVar: "fixed_12",  isSalaryStub: true,  salaryHint: "₹35,000–41,000/month", domain: null },
  { templateKey: "cross.accountant",    section: "salary",    description: "Accountant",                                 costCategory: "Salary", unitType: "Month",  inputVar: "fixed_12",  isSalaryStub: true,  salaryHint: "₹33,000–40,000/month", domain: null },
  { templateKey: "cross.capacity",      section: "programme", description: "Staff capacity building training",           costCategory: "Other",  unitType: "Annual", inputVar: "fixed_1",   costKey: "cross.staff_capacity_building",   domain: null },
  { templateKey: "cross.team_building", section: "programme", description: "Team building (3-day offsite)",              costCategory: "Other",  unitType: "Annual", inputVar: "fixed_1",   costKey: "cross.team_building_offsite",     domain: null },
  { templateKey: "cross.planning",      section: "programme", description: "Planning & review meetings",                 costCategory: "Other",  unitType: "Annual", inputVar: "fixed_1",   costKey: "cross.planning_review_meetings",  domain: null },
  { templateKey: "cross.crisis",        section: "programme", description: "Crisis intervention support",                costCategory: "Other",  unitType: "Annual", inputVar: "fixed_1",   costKey: "cross.crisis_intervention",       domain: null },
];

const ADMIN: TemplateSpec[] = [
  { templateKey: "admin.pm",           section: "admin_salary", description: "Project Manager / Director",                costCategory: "Salary", unitType: "Month",  inputVar: "fixed_12",  isSalaryStub: true,  salaryHint: "Enter actuals", isAutoGenerated: false, domain: null },
  { templateKey: "admin.finance",      section: "admin_salary", description: "Finance / Admin Officer",                  costCategory: "Salary", unitType: "Month",  inputVar: "fixed_12",  isSalaryStub: true,  salaryHint: "Enter actuals", isAutoGenerated: false, domain: null },
  { templateKey: "admin.office_rent",  section: "admin_other",  description: "Office rent",                              costCategory: "Other",  unitType: "Month",  inputVar: "fixed_12",  isSalaryStub: true,  isAutoGenerated: false, domain: null },
  { templateKey: "admin.utilities",    section: "admin_other",  description: "Utilities (electricity, water, internet)", costCategory: "Other",  unitType: "Month",  inputVar: "fixed_12",  isSalaryStub: true,  isAutoGenerated: false, domain: null },
  { templateKey: "admin.comms",        section: "admin_other",  description: "Communication (phone, printing)",          costCategory: "Other",  unitType: "Month",  inputVar: "fixed_12",  isSalaryStub: true,  isAutoGenerated: false, domain: null },
  { templateKey: "admin.audit",        section: "admin_other",  description: "Audit fees",                               costCategory: "Other",  unitType: "Annual", inputVar: "fixed_1",   isSalaryStub: true,  isAutoGenerated: false, domain: null },
  { templateKey: "admin.insurance",    section: "admin_other",  description: "Insurance",                                costCategory: "Nil",    unitType: "Annual", inputVar: "fixed_1",   isSalaryStub: true,  isAutoGenerated: false, domain: null },
  { templateKey: "admin.staff_travel", section: "admin_other",  description: "Staff travel (admin)",                     costCategory: "Other",  unitType: "Annual", inputVar: "fixed_1",   isSalaryStub: true,  isAutoGenerated: false, domain: null },
];

function withDomain(templates: TemplateSpec[], domain: string): TemplateSpec[] {
  return templates.map(t => ({ ...t, domain: t.domain === undefined ? domain : t.domain }));
}

export function getTemplatesForCity(city: string): TemplateSpec[] {
  return [
    ...withDomain(CHILDREN,             "Children"),
    ...withDomain(YOUTH,                "Youth"),
    ...withDomain(ELDERLY,              "Elderly"),
    ...withDomain(WR,                   "WelfareRights"),
    ...withDomain(crecheTemplates(city),"Creche"),
    ...CROSS,
    ...ADMIN,
  ];
}
