"use server";

import { auth } from "@/lib/auth";
import prisma from "@/lib/prisma";
import { generateBudgetLines } from "@/lib/budget-generator";
import type { BudgetSection, InflationType } from "@/app/generated/prisma/client";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";

export type CreateBudgetPayload = {
  name: string;
  city: string;
  domains: string[];
  years: 1 | 3;
  programmeInputs: Record<string, number>;
  includeCrossCutting: boolean;
};

export async function createBudget(payload: CreateBudgetPayload) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const [registryRows, templates] = await Promise.all([
    prisma.costRegistry.findMany({ where: { city: payload.city } }),
    prisma.lineTemplate.findMany({ where: { city: payload.city }, orderBy: { position: "asc" } }),
  ]);
  const registry: Record<string, number> = Object.fromEntries(registryRows.map(r => [r.itemKey, r.unitCost]));

  const eligibleTemplates = payload.includeCrossCutting
    ? templates
    : templates.filter(t => t.domain !== null);
  const lines = generateBudgetLines(payload.domains, payload.programmeInputs, payload.years, registry, eligibleTemplates);

  const pi = payload.programmeInputs;
  const budget = await prisma.budget.create({
    data: {
      name: payload.name,
      city: payload.city,
      partnerId: session.user.id,
      domains: payload.domains,
      years: payload.years,
      inputs: {
        create: {
          // Keep typed fields populated for backward compat with existing queries
          nSettlements:              Math.round(pi.nSettlements ?? 0),
          nClusters:                 Math.round(pi.nClusters ?? 0),
          nCLCs:                     Math.round(pi.nCLCs ?? 0),
          clcRentPerMonth:           Math.round(pi.clcRentPerMonth ?? 0),
          nYRCs:                     Math.round(pi.nYRCs ?? 0),
          yrcRentPerMonth:           Math.round(pi.yrcRentPerMonth ?? 0),
          nElderlyCentres:           Math.round(pi.nElderlyCentres ?? 0),
          nElderly:                  Math.round(pi.nElderly ?? 0),
          elderlyCentreRentPerMonth: Math.round(pi.elderlyCentreRentPerMonth ?? 0),
          cosPerCluster:             Math.round(pi.cosPerCluster ?? 0),
          rcRentPerMonth:            Math.round(pi.rcRentPerMonth ?? 0),
          nCreches:                  Math.round(pi.nCreches ?? 0),
          crecheRentPerMonth:        Math.round(pi.crecheRentPerMonth ?? 0),
          extraInputs:               pi,  // full flat map — source of truth going forward
        },
      },
      lines: {
        create: lines.map(l => ({
          domain: l.domain ?? undefined,
          section: l.section,
          position: l.position,
          description: l.description,
          costCategory: l.costCategory,
          unitType: l.unitType,
          isAutoGenerated: l.isAutoGenerated ?? true,
          salaryHint: l.salaryHint,
          notes: l.notes,
          y1Units: l.y1Units,
          y1UnitCost: l.y1UnitCost,
          y1AllocPct: l.y1AllocPct,
          y1Total: l.y1Total,
          y2Units: l.y2Units,
          y2UnitCost: l.y2UnitCost,
          y2AllocPct: l.y2AllocPct,
          y2Total: l.y2Total,
          y3Units: l.y3Units,
          y3UnitCost: l.y3UnitCost,
          y3AllocPct: l.y3AllocPct,
          y3Total: l.y3Total,
        })),
      },
    },
  });

  redirect(`/budget/${budget.id}`);
}

export async function updateLine(
  lineId: string,
  updates: {
    description?: string;
    y1Units?: number;
    y1UnitCost?: number;
    y1AllocPct?: number;
    y2Units?: number;
    y2UnitCost?: number;
    y2AllocPct?: number;
    y3Units?: number;
    y3UnitCost?: number;
    y3AllocPct?: number;
  }
) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const line = await prisma.budgetLine.findUnique({ where: { id: lineId }, select: { budgetId: true, budget: { select: { partnerId: true } }, costCategory: true } });
  if (!line || line.budget.partnerId !== session.user.id) throw new Error("Not found");

  const y1Total = Math.round((updates.y1Units ?? 0) * (updates.y1UnitCost ?? 0) * (updates.y1AllocPct ?? 1));
  const y2Total = Math.round((updates.y2Units ?? 0) * (updates.y2UnitCost ?? 0) * (updates.y2AllocPct ?? 1));
  const y3Total = Math.round((updates.y3Units ?? 0) * (updates.y3UnitCost ?? 0) * (updates.y3AllocPct ?? 1));

  await prisma.budgetLine.update({
    where: { id: lineId },
    data: { ...updates, y1Total, y2Total, y3Total },
  });
  revalidatePath(`/budget/${line.budgetId}`);
}

export async function addLine(
  budgetId: string,
  data: {
    domain?: string;
    section: BudgetSection;
    description: string;
    costCategory: InflationType;
    unitType: string;
    y1Units?: number;
    y1UnitCost?: number;
  }
) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const budget = await prisma.budget.findUnique({
    where: { id: budgetId },
    select: {
      partnerId: true,
      years: true,
      lines: { select: { position: true }, orderBy: { position: "desc" }, take: 1 },
    },
  });
  if (!budget || budget.partnerId !== session.user.id) throw new Error("Not found");

  const rate = data.costCategory === "Salary" ? 0.10 : data.costCategory === "Other" ? 0.05 : 0;
  const y1Units = data.y1Units ?? 0;
  const y1UnitCost = data.y1UnitCost ?? 0;
  const y1Total = Math.round(y1Units * y1UnitCost);
  const y2UnitCost = budget.years >= 3 ? Math.round(y1UnitCost * (1 + rate)) : 0;
  const y3UnitCost = budget.years >= 3 ? Math.round(y2UnitCost * (1 + rate)) : 0;
  const y2Total = budget.years >= 3 ? Math.round(y1Units * y2UnitCost) : 0;
  const y3Total = budget.years >= 3 ? Math.round(y1Units * y3UnitCost) : 0;

  const nextPos = (budget.lines[0]?.position ?? 0) + 1;
  const line = await prisma.budgetLine.create({
    data: {
      budgetId,
      domain: data.domain,
      section: data.section,
      description: data.description,
      costCategory: data.costCategory,
      unitType: data.unitType,
      position: nextPos,
      isAutoGenerated: false,
      y1Units, y1UnitCost, y1AllocPct: 1, y1Total,
      y2Units: budget.years >= 3 ? y1Units : 0,
      y2UnitCost, y2AllocPct: 1, y2Total,
      y3Units: budget.years >= 3 ? y1Units : 0,
      y3UnitCost, y3AllocPct: 1, y3Total,
    },
  });
  revalidatePath(`/budget/${budgetId}`);
  return line;
}

export async function deleteLine(lineId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const line = await prisma.budgetLine.findUnique({ where: { id: lineId }, select: { budgetId: true, budget: { select: { partnerId: true } } } });
  if (!line || line.budget.partnerId !== session.user.id) throw new Error("Not found");

  await prisma.budgetLine.delete({ where: { id: lineId } });
  revalidatePath(`/budget/${line.budgetId}`);
}

export async function finalizeBudget(budgetId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const budget = await prisma.budget.findUnique({ where: { id: budgetId }, select: { partnerId: true } });
  if (!budget || budget.partnerId !== session.user.id) throw new Error("Not found");

  await prisma.budget.update({ where: { id: budgetId }, data: { status: "final" } });
  revalidatePath(`/budget/${budgetId}`);
}

export async function deleteBudget(budgetId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const budget = await prisma.budget.findUnique({ where: { id: budgetId }, select: { partnerId: true } });
  if (!budget || budget.partnerId !== session.user.id) throw new Error("Not found");

  await prisma.budget.delete({ where: { id: budgetId } });
  redirect("/budget");
}
