"use server";

import { auth } from "@/lib/auth";
import prisma from "@/lib/prisma";
import { generateBudgetLines, DEFAULT_INFLATION_RATES, activeYearBands } from "@/lib/budget-generator";
import type { BudgetSection, BudgetLineCadence, InflationType } from "@/app/generated/prisma/client";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import type { ParsedBudget } from "@/lib/budget/importTemplate";

export type CreateBudgetPayload = {
  name: string;
  city: string;
  domains: string[];
  horizonMonths: number;
  applyInflation: boolean;
  programmeInputs: Record<string, number>;
  includeCrossCutting: boolean;
  /** Sparse delta keyed by CostRegistry.itemKey. {} when partner picked "Standard". */
  costOverrides?: Record<string, number>;
};

export async function createBudget(payload: CreateBudgetPayload) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const horizonMonths = Math.min(60, Math.max(1, Math.round(payload.horizonMonths)));
  // Keep `years` in sync for legacy read paths (list pages, report-actions
  // grantYear lookups, etc.). years = number of year-bands the horizon covers.
  const years = activeYearBands(horizonMonths);

  const [registryRows, templates] = await Promise.all([
    prisma.costRegistry.findMany({ where: { city: payload.city } }),
    prisma.lineTemplate.findMany({ where: { city: payload.city }, orderBy: { position: "asc" } }),
  ]);
  // Snapshot the full registry at create time. Stored on Budget.costSnapshot
  // so future regenerate / scale-up actions reproduce the partner's basis
  // even if the registry has since changed.
  const costSnapshot: Record<string, number> = Object.fromEntries(registryRows.map(r => [r.itemKey, r.unitCost]));
  // Drop overrides for keys not in the registry so we never persist orphan keys.
  const rawOverrides = payload.costOverrides ?? {};
  const costOverrides: Record<string, number> = {};
  for (const [k, v] of Object.entries(rawOverrides)) {
    if (typeof v === "number" && Number.isFinite(v) && k in costSnapshot) {
      costOverrides[k] = v;
    }
  }
  // Generator reads snapshot ∪ overrides — overrides win where present.
  const mergedRegistry: Record<string, number> = { ...costSnapshot, ...costOverrides };

  const eligibleTemplates = payload.includeCrossCutting
    ? templates
    : templates.filter(t => t.domain !== null);
  const lines = generateBudgetLines(
    payload.domains,
    payload.programmeInputs,
    { horizonMonths, applyInflation: payload.applyInflation, inflationRates: DEFAULT_INFLATION_RATES },
    mergedRegistry,
    eligibleTemplates,
  );

  const pi = payload.programmeInputs;
  const budget = await prisma.budget.create({
    data: {
      name: payload.name,
      city: payload.city,
      partnerId: session.user.id,
      domains: payload.domains,
      years,
      horizonMonths,
      applyInflation: payload.applyInflation,
      costSnapshot,
      costOverrides,
      // Inflation rates fall back to the Prisma schema defaults (10/5/0) if omitted.
      inputs: {
        create: {
          // Keep typed fields populated for backward compat with existing queries
          nSettlements:              Math.round(pi.nSettlements ?? 0),
          nClusters:                 Math.round(pi.nClusters ?? 0),
          nCLCs:                     Math.round(pi.nCLCs ?? 0),
          clcRentPerMonth:           Math.round(pi.clcRentPerMonth ?? 0),
          nYRCs:                     Math.round(pi.nYRCs ?? 0),
          yrcRentPerMonth:           Math.round(pi.yrcRentPerMonth ?? 0),
          nElderlyCentres:           Math.round(pi.nElderlyCentres ?? 0),
          nElderly:                  Math.round(pi.nElderly ?? 0),
          elderlyCentreRentPerMonth: Math.round(pi.elderlyCentreRentPerMonth ?? 0),
          cosPerCluster:             Math.round(pi.cosPerCluster ?? 0),
          rcRentPerMonth:            Math.round(pi.rcRentPerMonth ?? 0),
          nCreches:                  Math.round(pi.nCreches ?? 0),
          crecheRentPerMonth:        Math.round(pi.crecheRentPerMonth ?? 0),
          extraInputs:               pi,  // full flat map — source of truth going forward
        },
      },
      lines: {
        create: lines.map(l => ({
          domain: l.domain ?? undefined,
          section: l.section,
          position: l.position,
          description: l.description,
          costCategory: l.costCategory,
          unitType: l.unitType,
          isAutoGenerated: l.isAutoGenerated ?? true,
          salaryHint: l.salaryHint,
          notes: l.notes,
          templateKey: l.templateKey,
          cadence: l.cadence,
          plannedMonths: l.plannedMonths,
          y1Units: l.y1Units,
          y1UnitCost: l.y1UnitCost,
          y1AllocPct: l.y1AllocPct,
          y1Total: l.y1Total,
          y2Units: l.y2Units,
          y2UnitCost: l.y2UnitCost,
          y2AllocPct: l.y2AllocPct,
          y2Total: l.y2Total,
          y3Units: l.y3Units,
          y3UnitCost: l.y3UnitCost,
          y3AllocPct: l.y3AllocPct,
          y3Total: l.y3Total,
          y4Units: l.y4Units,
          y4UnitCost: l.y4UnitCost,
          y4AllocPct: l.y4AllocPct,
          y4Total: l.y4Total,
          y5Units: l.y5Units,
          y5UnitCost: l.y5UnitCost,
          y5AllocPct: l.y5AllocPct,
          y5Total: l.y5Total,
        })),
      },
    },
  });

  redirect(`/budget/${budget.id}`);
}

/**
 * Create a budget from a parsed (imported) Excel template. Mirrors createBudget's
 * write but uses the parsed lines/inputs verbatim instead of the generator, and
 * stamps importedAt so a future "regenerate from inputs" knows the lines carry
 * hand edits. Returns the new id (no redirect) so the client can navigate.
 */
export async function createBudgetFromImport(parsed: ParsedBudget): Promise<{ id: string }> {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const horizonMonths = Math.min(60, Math.max(1, Math.round(parsed.horizonMonths || 12)));
  const years = activeYearBands(horizonMonths);
  const pi = parsed.inputs ?? {};
  const num = (k: string) => Math.round(Number(pi[k]) || 0);

  const budget = await prisma.budget.create({
    data: {
      name: parsed.name,
      city: parsed.city,
      partnerId: session.user.id,
      domains: parsed.domains,
      years,
      horizonMonths,
      applyInflation: parsed.applyInflation,
      inflationSalaryPct: parsed.inflationPct.Salary,
      inflationOtherPct: parsed.inflationPct.Other,
      inflationNilPct: parsed.inflationPct.Nil,
      costSnapshot: parsed.costSnapshot,
      costOverrides: parsed.costOverrides,
      importedAt: new Date(),
      inputs: {
        create: {
          nSettlements: num("nSettlements"), nClusters: num("nClusters"),
          nCLCs: num("nCLCs"), clcRentPerMonth: num("clcRentPerMonth"),
          nYRCs: num("nYRCs"), yrcRentPerMonth: num("yrcRentPerMonth"),
          nElderlyCentres: num("nElderlyCentres"), nElderly: num("nElderly"),
          elderlyCentreRentPerMonth: num("elderlyCentreRentPerMonth"),
          cosPerCluster: num("cosPerCluster"), rcRentPerMonth: num("rcRentPerMonth"),
          nCreches: num("nCreches"), crecheRentPerMonth: num("crecheRentPerMonth"),
          extraInputs: pi,
        },
      },
      lines: {
        create: parsed.lines
          .slice()
          .sort((a, b) => a.position - b.position)
          .map((l, i) => ({
            domain: l.domain ?? undefined,
            section: l.section as BudgetSection,
            position: i,
            description: l.description,
            costCategory: l.costCategory as InflationType,
            unitType: l.unitType,
            isAutoGenerated: false,
            salaryHint: l.salaryHint,
            notes: l.notes,
            templateKey: l.templateKey,
            cadence: l.cadence as BudgetLineCadence,
            plannedMonths: l.plannedMonths,
            y1Units: l.y1Units, y1UnitCost: l.y1UnitCost, y1AllocPct: l.y1AllocPct, y1Total: l.y1Total,
            y2Units: l.y2Units, y2UnitCost: l.y2UnitCost, y2AllocPct: l.y2AllocPct, y2Total: l.y2Total,
            y3Units: l.y3Units, y3UnitCost: l.y3UnitCost, y3AllocPct: l.y3AllocPct, y3Total: l.y3Total,
            y4Units: l.y4Units, y4UnitCost: l.y4UnitCost, y4AllocPct: l.y4AllocPct, y4Total: l.y4Total,
            y5Units: l.y5Units, y5UnitCost: l.y5UnitCost, y5AllocPct: l.y5AllocPct, y5Total: l.y5Total,
          })),
      },
    },
  });

  revalidatePath("/budget");
  return { id: budget.id };
}

/**
 * Normalises a (cadence, plannedMonths) pair from the client into a shape
 * the DB will accept: dedupe, sort, clamp to 1..12, enforce arity per cadence.
 * Throws on bad input — keep the server honest even if the UI guards.
 */
function normaliseCadence(
  cadence: BudgetLineCadence,
  plannedMonths: number[] | undefined,
): { cadence: BudgetLineCadence; plannedMonths: number[] } {
  if (cadence === "monthly") return { cadence, plannedMonths: [] };
  const cleaned = Array.from(new Set((plannedMonths ?? [])
    .map(m => Math.round(m))
    .filter(m => Number.isFinite(m) && m >= 1 && m <= 12)))
    .sort((a, b) => a - b);
  if (cadence === "one_time" && cleaned.length !== 1) {
    throw new Error("one_time cadence requires exactly one planned month (1..12)");
  }
  if (cadence === "seasonal" && cleaned.length < 2) {
    throw new Error("seasonal cadence requires at least two planned months");
  }
  return { cadence, plannedMonths: cleaned };
}

export async function updateLine(
  lineId: string,
  updates: {
    description?: string;
    // domain: pass null to mark the row as cross-cutting, string to attach it
    // to a specific domain card. Omit to leave unchanged.
    domain?: string | null;
    // Cadence: omit to leave unchanged. Pass cadence + plannedMonths together.
    cadence?: BudgetLineCadence;
    plannedMonths?: number[];
    y1Units?: number; y1UnitCost?: number; y1AllocPct?: number;
    y2Units?: number; y2UnitCost?: number; y2AllocPct?: number;
    y3Units?: number; y3UnitCost?: number; y3AllocPct?: number;
    y4Units?: number; y4UnitCost?: number; y4AllocPct?: number;
    y5Units?: number; y5UnitCost?: number; y5AllocPct?: number;
  }
) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const line = await prisma.budgetLine.findUnique({ where: { id: lineId }, select: { budgetId: true, budget: { select: { partnerId: true } }, costCategory: true } });
  if (!line || line.budget.partnerId !== session.user.id) throw new Error("Not found");

  const total = (u?: number, c?: number, a?: number) => Math.round((u ?? 0) * (c ?? 0) * (a ?? 1));
  const y1Total = total(updates.y1Units, updates.y1UnitCost, updates.y1AllocPct);
  const y2Total = total(updates.y2Units, updates.y2UnitCost, updates.y2AllocPct);
  const y3Total = total(updates.y3Units, updates.y3UnitCost, updates.y3AllocPct);
  const y4Total = total(updates.y4Units, updates.y4UnitCost, updates.y4AllocPct);
  const y5Total = total(updates.y5Units, updates.y5UnitCost, updates.y5AllocPct);

  // Strip + re-validate the cadence pair so we never persist {one_time, []} etc.
  const { cadence: _c, plannedMonths: _pm, ...rest } = updates;
  const cadencePatch = updates.cadence !== undefined
    ? normaliseCadence(updates.cadence, updates.plannedMonths)
    : {};

  await prisma.budgetLine.update({
    where: { id: lineId },
    data: { ...rest, ...cadencePatch, y1Total, y2Total, y3Total, y4Total, y5Total },
  });
  revalidatePath(`/budget/${line.budgetId}`);
}

export async function addLine(
  budgetId: string,
  data: {
    domain?: string;
    section: BudgetSection;
    description: string;
    costCategory: InflationType;
    unitType: string;
    y1Units?: number;
    y1UnitCost?: number;
    cadence?: BudgetLineCadence;
    plannedMonths?: number[];
  }
) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const budget = await prisma.budget.findUnique({
    where: { id: budgetId },
    select: {
      partnerId: true,
      horizonMonths: true,
      applyInflation: true,
      inflationSalaryPct: true,
      inflationOtherPct: true,
      inflationNilPct: true,
      lines: { select: { position: true }, orderBy: { position: "desc" }, take: 1 },
    },
  });
  if (!budget || budget.partnerId !== session.user.id) throw new Error("Not found");

  const ratePct =
    data.costCategory === "Salary" ? budget.inflationSalaryPct
    : data.costCategory === "Other" ? budget.inflationOtherPct
    : budget.inflationNilPct;
  const rate = budget.applyInflation ? ratePct / 100 : 0;

  const y1Units = data.y1Units ?? 0;
  const y1UnitCost = data.y1UnitCost ?? 0;

  const yearFactor = (k: number): number => {
    const full = Math.floor(budget.horizonMonths / 12);
    const tail = budget.horizonMonths - full * 12;
    if (k <= full) return 1;
    if (k === full + 1 && tail > 0) return tail / 12;
    return 0;
  };

  const bandData = (k: number) => {
    const factor = yearFactor(k);
    if (factor === 0) return { units: 0, cost: 0, total: 0 };
    const units = y1Units * factor;
    const cost  = Math.round(y1UnitCost * Math.pow(1 + rate, k - 1));
    return { units, cost, total: Math.round(units * cost) };
  };

  const b1 = { units: y1Units, cost: y1UnitCost, total: Math.round(y1Units * y1UnitCost * yearFactor(1)) };
  const b2 = bandData(2);
  const b3 = bandData(3);
  const b4 = bandData(4);
  const b5 = bandData(5);

  const nextPos = (budget.lines[0]?.position ?? 0) + 1;
  // Defaults: Capex section → one_time month 1, everything else → monthly.
  // Partner can override via the cadence picker in the add-line form.
  const fallbackCadence: BudgetLineCadence = data.section === "capex" ? "one_time" : "monthly";
  const cadencePatch = normaliseCadence(
    data.cadence ?? fallbackCadence,
    data.cadence ? data.plannedMonths : (data.section === "capex" ? [1] : []),
  );
  const line = await prisma.budgetLine.create({
    data: {
      budgetId,
      domain: data.domain,
      section: data.section,
      description: data.description,
      costCategory: data.costCategory,
      unitType: data.unitType,
      position: nextPos,
      isAutoGenerated: false,
      ...cadencePatch,
      y1Units: b1.units, y1UnitCost: b1.cost, y1AllocPct: 1, y1Total: b1.total,
      y2Units: b2.units, y2UnitCost: b2.cost, y2AllocPct: 1, y2Total: b2.total,
      y3Units: b3.units, y3UnitCost: b3.cost, y3AllocPct: 1, y3Total: b3.total,
      y4Units: b4.units, y4UnitCost: b4.cost, y4AllocPct: 1, y4Total: b4.total,
      y5Units: b5.units, y5UnitCost: b5.cost, y5AllocPct: 1, y5Total: b5.total,
    },
  });
  revalidatePath(`/budget/${budgetId}`);
  return line;
}

export async function deleteLine(lineId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const line = await prisma.budgetLine.findUnique({ where: { id: lineId }, select: { budgetId: true, budget: { select: { partnerId: true } } } });
  if (!line || line.budget.partnerId !== session.user.id) throw new Error("Not found");

  await prisma.budgetLine.delete({ where: { id: lineId } });
  revalidatePath(`/budget/${line.budgetId}`);
}

export async function finalizeBudget(budgetId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const budget = await prisma.budget.findUnique({ where: { id: budgetId }, select: { partnerId: true } });
  if (!budget || budget.partnerId !== session.user.id) throw new Error("Not found");

  await prisma.budget.update({ where: { id: budgetId }, data: { status: "final" } });
  revalidatePath(`/budget/${budgetId}`);
}

export async function deleteBudget(budgetId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const budget = await prisma.budget.findUnique({ where: { id: budgetId }, select: { partnerId: true } });
  if (!budget || budget.partnerId !== session.user.id) throw new Error("Not found");

  await prisma.budget.delete({ where: { id: budgetId } });
  redirect("/budget");
}
