/**
 * Backfill `BudgetLine.templateKey` for rows generated before the field existed.
 *
 * Matching strategy:
 *   1. Skip rows that already have a templateKey.
 *   2. Skip rows that are not auto-generated (manual user adds + reallocations).
 *   3. Match LineTemplate by (city, domain, description). Description is unique
 *      within a (city, domain) — verified via @@unique([city, templateKey]) +
 *      manual review of seed data.
 *
 * Usage:
 *   npx tsx scripts/backfill-budgetline-templatekey.ts         # dry run
 *   npx tsx scripts/backfill-budgetline-templatekey.ts --apply # write
 */
import { PrismaClient } from "../app/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

const APPLY = process.argv.includes("--apply");

async function main() {
  const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
  const prisma = new PrismaClient({ adapter });

  const lines = await prisma.budgetLine.findMany({
    where: { templateKey: null, isAutoGenerated: true },
    select: {
      id: true,
      domain: true,
      description: true,
      budget: { select: { city: true } },
    },
  });
  console.log(`Found ${lines.length} candidate BudgetLine rows missing templateKey.`);

  // Index LineTemplate by (city, domain, description)
  const templates = await prisma.lineTemplate.findMany({
    select: { city: true, domain: true, description: true, templateKey: true },
  });
  const idx = new Map<string, string>();
  for (const t of templates) {
    idx.set(`${t.city}|${t.domain ?? "_"}|${t.description}`, t.templateKey);
  }
  console.log(`Indexed ${templates.length} LineTemplate rows.`);

  let matched = 0;
  let unmatched = 0;
  const unmatchedSamples: Array<{ id: string; city: string; domain: string | null; description: string }> = [];
  const updates: Array<{ id: string; templateKey: string }> = [];

  for (const l of lines) {
    const key = `${l.budget.city}|${l.domain ?? "_"}|${l.description}`;
    const tk = idx.get(key);
    if (tk) {
      matched++;
      updates.push({ id: l.id, templateKey: tk });
    } else {
      unmatched++;
      if (unmatchedSamples.length < 10) {
        unmatchedSamples.push({ id: l.id, city: l.budget.city, domain: l.domain, description: l.description });
      }
    }
  }

  console.log(`Matched: ${matched}, unmatched: ${unmatched}`);
  if (unmatchedSamples.length) {
    console.log("Unmatched samples (first 10):");
    for (const s of unmatchedSamples) console.log(`  ${s.id} | ${s.city} | ${s.domain ?? "(null)"} | ${s.description}`);
  }

  if (!APPLY) {
    console.log("\nDry run — pass --apply to write.");
    return;
  }

  // Sequential updates (Prisma batch-transaction timeout option wasn't honoured here)
  for (let i = 0; i < updates.length; i++) {
    const u = updates[i];
    await prisma.budgetLine.update({ where: { id: u.id }, data: { templateKey: u.templateKey } });
    if ((i + 1) % 50 === 0 || i === updates.length - 1) {
      console.log(`  Wrote ${i + 1}/${updates.length}`);
    }
  }
  console.log("Done.");
}

main().catch(e => { console.error(e); process.exit(1); });
