/**
 * Apply the Urban Creche V.2 (May-25) standard to the LIVE Bangalore data, with
 * a full change-log entry per unit-cost change (CostRegistryHistory).
 *
 * Carries NO numbers of its own — it syncs the live CostRegistry to the updated
 * seed defaults (lib/budget-costs.ts) and additively creates any missing
 * LineTemplates from the seed (lib/line-template-seeds.ts). So the seed files
 * are the single source of truth; this script just pushes them to live + logs.
 *
 * What changes for Creche in V.2:
 *   - Recurring op-cost refresh (feeding, egg, gas, hygiene, play, flexi, setup)
 *   - Training split: training retargeted + new review_meeting item/template
 *   - Supervisory roles: Logistics / Training / Safety / PM / MIS added
 *     (existing supervisor & coordinator travel bumped to include phone)
 *
 * Idempotent: a second run finds nothing to change and logs nothing.
 *
 * Ordering: migration 20260703000000_cost_registry_provenance (the
 * CostRegistryHistory table) MUST be applied first, or the log writes fail.
 *
 * Usage:
 *   npx tsx scripts/reseed-creche-v2.ts            # dry run (default)
 *   npx tsx scripts/reseed-creche-v2.ts --apply    # write + log
 */
import { PrismaClient } from "../app/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { getDefaultsForCity } from "../lib/budget-costs";
import { getTemplatesForCity } from "../lib/line-template-seeds";
import { logCostChange } from "../lib/budget/costHistory";
import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

const APPLY = process.argv.includes("--apply");
const CITY = "Bangalore";
const SOURCE = "Urban Creche V.2 May25";

async function main() {
  const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
  const prisma = new PrismaClient({ adapter });
  console.log(`\n=== Creche V.2 reseed (${CITY}) — ${APPLY ? "APPLY" : "DRY RUN"} ===\n`);

  // ── 1. Registry: sync Creche defaults → live, logging every diff ───────────
  const crecheDefaults = getDefaultsForCity(CITY).filter(c => c.domain === "Creche");
  let changed = 0;
  for (const d of crecheDefaults) {
    const existing = await prisma.costRegistry.findUnique({
      where: { city_itemKey: { city: CITY, itemKey: d.itemKey } },
    });
    const oldCost = existing?.unitCost ?? null;
    if (oldCost === d.unitCost) continue; // unchanged — skip silently
    changed++;
    console.log(`  ${oldCost === null ? "+" : "~"}  ${d.itemKey.padEnd(42)} ${oldCost ?? "(new)"} → ${d.unitCost}`);
    if (!APPLY) continue;
    await prisma.$transaction(async (tx) => {
      await tx.costRegistry.upsert({
        where: { city_itemKey: { city: CITY, itemKey: d.itemKey } },
        create: { city: CITY, domain: "Creche", itemKey: d.itemKey, unitCost: d.unitCost, unit: d.unit, effectiveYear: 2025, notes: d.notes ?? null },
        update: { unitCost: d.unitCost, unit: d.unit, notes: d.notes ?? null },
      });
      await logCostChange(tx, {
        city: CITY, domain: "Creche", itemKey: d.itemKey,
        oldCost, newCost: d.unitCost, source: SOURCE,
        reason: oldCost === null ? "V.2 new line" : "V.2 unit-cost revision",
      });
    });
  }
  console.log(`\n  ${APPLY ? "Applied" : "Would change"} ${changed} Creche unit cost(s).`);

  // ── 2. Templates: additively create any missing (position = seed index) ────
  // Create only the missing rows, sequentially — upserting the full ~100-spec
  // list in one transaction exceeds Neon's 5s interactive-transaction budget.
  const specs = getTemplatesForCity(CITY);
  const liveKeys = new Set(
    (await prisma.lineTemplate.findMany({ where: { city: CITY }, select: { templateKey: true } }))
      .map(t => t.templateKey),
  );
  const missing = specs
    .map((t, position) => ({ t, position }))
    .filter(({ t }) => !liveKeys.has(t.templateKey));
  for (const { t } of missing) console.log(`  + template ${t.templateKey} (${t.description})`);
  if (APPLY) {
    for (const { t, position } of missing) {
      await prisma.lineTemplate.create({
        data: {
          city: CITY, templateKey: t.templateKey, position,
          section: t.section as never, description: t.description,
          costCategory: t.costCategory as never, unitType: t.unitType,
          notes: t.notes ?? null, salaryHint: t.salaryHint ?? null,
          isAutoGenerated: t.isAutoGenerated ?? true,
          domain: (t.domain as never) ?? null,
          inputVar: t.inputVar ?? "fixed_1", inputMonthly: t.inputMonthly ?? false,
          supervisorRatioKey: t.supervisorRatioKey ?? null,
          isSalaryStub: t.isSalaryStub ?? false, userInputCost: t.userInputCost ?? null,
          costKey: t.costKey ?? null, costKey2: t.costKey2 ?? null, costKey3: t.costKey3 ?? null,
          costMonthly: t.costMonthly ?? false, workerRatioKey: t.workerRatioKey ?? null,
          bufferKey: t.bufferKey ?? null, costPctOf: t.costPctOf ?? null, costPct: t.costPct ?? null,
          y1UnitsZero: t.y1UnitsZero ?? false,
        },
      });
    }
  }
  console.log(`  ${APPLY ? "Created" : "Would create"} ${missing.length} template(s).`);

  // ── 3. Fix the training template description (was "& review meetings") ─────
  const training = await prisma.lineTemplate.findUnique({
    where: { city_templateKey: { city: CITY, templateKey: "creche.training" } },
  });
  if (training && /review/i.test(training.description)) {
    console.log(`  ~ template creche.training description → "Training of creche workers"`);
    if (APPLY) {
      await prisma.lineTemplate.update({
        where: { id: training.id },
        data: { description: "Training of creche workers" },
      });
    }
  }

  console.log("");
  await prisma.$disconnect();
}

main().catch((e) => { console.error(e); process.exit(1); });
