// Idempotent apply for the two new standalone budget domains (RO_Water +
// Sanitation_Complex): upserts their CostRegistry items, the inp.* programme
// inputs, the LineTemplate rows, and the BudgetDomainConfig rows — for
// Bangalore + Chennai. Mirrors the admin seed* functions (create-only, never
// overwrites edits). Safe to re-run.
//   npx tsx scripts/seed-water-sanitation-domains.ts
import { config } from "dotenv";
config({ path: ".env.local" });
import { PrismaClient } from "../app/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { DEFAULT_COSTS } from "../lib/budget-costs";
import { getTemplatesForCity } from "../lib/line-template-seeds";
const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL! }) });

const DOMAINS = ["RO_Water", "Sanitation_Complex"];
const CITIES = ["Bangalore", "Chennai"];

const NEW_PROG_INPUTS = [
  { itemKey: "inp.nRO_Plants",                    unit: "count",   unitCost: 1, notes: "No. of RO water plants",       displayGroup: "facilities" },
  { itemKey: "inp.roPlantRentPerMonth",           unit: "₹/month", unitCost: 0, notes: "RO plant site rent / mo",      displayGroup: "facilities" },
  { itemKey: "inp.nSanitationComplexes",          unit: "count",   unitCost: 1, notes: "No. of sanitation complexes",  displayGroup: "facilities" },
  { itemKey: "inp.sanitationComplexRentPerMonth", unit: "₹/month", unitCost: 0, notes: "Sanitation complex rent / mo", displayGroup: "facilities" },
];

const NEW_DOMAINS = [
  { key: "RO_Water",           label: "RO Water Plant",     description: "Community RO drinking-water plant",    position: 6, beneficiaryLabel: "Households", beneficiaryVar: "nRO_Plants",          beneficiaryMult: 500 },
  { key: "Sanitation_Complex", label: "Sanitation Complex", description: "Toilet + bath + laundry + RO complex", position: 7, beneficiaryLabel: "Households", beneficiaryVar: "nSanitationComplexes", beneficiaryMult: 420 },
];

async function main() {
  const regItems = DEFAULT_COSTS.filter(c => c.domain && DOMAINS.includes(c.domain));
  for (const city of CITIES) {
    let reg = 0, pin = 0, tpl = 0, dom = 0;
    // 1. CostRegistry — domain cost items
    for (const c of regItems) {
      await prisma.costRegistry.upsert({
        where: { city_itemKey: { city, itemKey: c.itemKey } },
        create: { city, domain: c.domain ?? undefined, itemKey: c.itemKey, unitCost: c.unitCost, unit: c.unit, effectiveYear: 2025, notes: c.notes },
        update: {},
      });
      reg++;
    }
    // 2. CostRegistry — programme inputs (inp.*)
    for (const d of NEW_PROG_INPUTS) {
      await prisma.costRegistry.upsert({
        where: { city_itemKey: { city, itemKey: d.itemKey } },
        create: { city, domain: null, effectiveYear: 2025, ...d },
        update: { displayGroup: d.displayGroup, notes: d.notes },
      });
      pin++;
    }
    // 3. LineTemplate — position = index in the full per-city template list
    const all = getTemplatesForCity(city);
    for (let i = 0; i < all.length; i++) {
      const t = all[i];
      if (!t.domain || !DOMAINS.includes(t.domain)) continue;
      await prisma.lineTemplate.upsert({
        where: { city_templateKey: { city, templateKey: t.templateKey } },
        update: {},
        create: {
          city, templateKey: t.templateKey, position: i,
          section: t.section as never, description: t.description, costCategory: t.costCategory as never,
          unitType: t.unitType, notes: t.notes ?? null, salaryHint: t.salaryHint ?? null,
          isAutoGenerated: t.isAutoGenerated ?? true, domain: (t.domain as never) ?? null,
          inputVar: t.inputVar ?? "fixed_1", inputMonthly: t.inputMonthly ?? false,
          supervisorRatioKey: t.supervisorRatioKey ?? null, isSalaryStub: t.isSalaryStub ?? false,
          userInputCost: t.userInputCost ?? null, costKey: t.costKey ?? null, costKey2: t.costKey2 ?? null,
          costKey3: t.costKey3 ?? null, costMonthly: t.costMonthly ?? false, workerRatioKey: t.workerRatioKey ?? null,
          bufferKey: t.bufferKey ?? null, costPctOf: t.costPctOf ?? null, costPct: t.costPct ?? null,
          y1UnitsZero: t.y1UnitsZero ?? false, applyY2: t.applyY2 ?? true, applyY3: t.applyY3 ?? true,
        },
      });
      tpl++;
    }
    // Self-heal already-seeded one-time capex (seed upsert is create-only): setup
    // capex is Y1-only, so it must not re-charge in Y2/Y3.
    const fixed = await prisma.lineTemplate.updateMany({
      where: { city, domain: { in: DOMAINS }, section: "capex", y1UnitsZero: false },
      data: { applyY2: false, applyY3: false },
    });
    console.log(`  ${city}: one-time capex Y1-only fix → ${fixed.count} rows`);
    // 4. BudgetDomainConfig
    for (const d of NEW_DOMAINS) {
      await prisma.budgetDomainConfig.upsert({
        where: { city_key: { city, key: d.key } },
        create: { city, isActive: true, ...d },
        update: {},
      });
      dom++;
    }
    console.log(`${city}: registry=${reg} progInputs=${pin} templates=${tpl} domains=${dom}`);
  }
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
