/**
 * Seeds LineTemplate rows for each city.
 * Run:  npx tsx scripts/seed-line-templates.ts [bangalore|chennai|all]
 *
 * Uses upsert on (city, templateKey) so safe to re-run.
 */
import { config } from "dotenv";
config({ path: ".env.local" });

import { Pool } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../app/generated/prisma/client";
import { getTemplatesForCity } from "../lib/line-template-seeds";

const pool = new Pool({ connectionString: process.env.MIGRATE_DATABASE_URL!, max: 1 });
const adapter = new PrismaPg(pool, { schema: undefined });
const prisma = new PrismaClient({ adapter } as never);

async function seedCity(city: string) {
  console.log(`\nSeeding templates for ${city}…`);

  const specs = getTemplatesForCity(city);
  let upserted = 0;

  for (const [position, t] of specs.entries()) {
    await prisma.lineTemplate.upsert({
      where: { city_templateKey: { city, templateKey: t.templateKey } },
      update: {
        section:            t.section as never,
        description:        t.description,
        costCategory:       t.costCategory as never,
        unitType:           t.unitType,
        notes:              t.notes ?? null,
        salaryHint:         t.salaryHint ?? null,
        isAutoGenerated:    t.isAutoGenerated ?? true,
        domain:             (t.domain as never) ?? null,
        inputVar:           t.inputVar ?? "fixed_1",
        inputMonthly:       t.inputMonthly ?? false,
        supervisorRatioKey: t.supervisorRatioKey ?? null,
        isSalaryStub:       t.isSalaryStub ?? false,
        userInputCost:      t.userInputCost ?? null,
        costKey:            t.costKey ?? null,
        costKey2:           t.costKey2 ?? null,
        costKey3:           t.costKey3 ?? null,
        costMonthly:        t.costMonthly ?? false,
        workerRatioKey:     t.workerRatioKey ?? null,
        bufferKey:          t.bufferKey ?? null,
        costPctOf:          t.costPctOf ?? null,
        costPct:            t.costPct ?? null,
        y1UnitsZero:        t.y1UnitsZero ?? false,
      },
      create: {
        city,
        templateKey:        t.templateKey,
        position,
        section:            t.section as never,
        description:        t.description,
        costCategory:       t.costCategory as never,
        unitType:           t.unitType,
        notes:              t.notes ?? null,
        salaryHint:         t.salaryHint ?? null,
        isAutoGenerated:    t.isAutoGenerated ?? true,
        domain:             (t.domain as never) ?? null,
        inputVar:           t.inputVar ?? "fixed_1",
        inputMonthly:       t.inputMonthly ?? false,
        supervisorRatioKey: t.supervisorRatioKey ?? null,
        isSalaryStub:       t.isSalaryStub ?? false,
        userInputCost:      t.userInputCost ?? null,
        costKey:            t.costKey ?? null,
        costKey2:           t.costKey2 ?? null,
        costKey3:           t.costKey3 ?? null,
        costMonthly:        t.costMonthly ?? false,
        workerRatioKey:     t.workerRatioKey ?? null,
        bufferKey:          t.bufferKey ?? null,
        costPctOf:          t.costPctOf ?? null,
        costPct:            t.costPct ?? null,
        y1UnitsZero:        t.y1UnitsZero ?? false,
      },
    });
    upserted++;
  }

  console.log(`  ✓ ${upserted} templates upserted for ${city}`);
}

async function main() {
  const arg = process.argv[2] ?? "all";
  if (arg === "all" || arg === "bangalore") await seedCity("Bangalore");
  if (arg === "all" || arg === "chennai")   await seedCity("Chennai");
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect().then(() => pool.end()));
