// Idempotent apply for the AfterSchoolCentre budget domain: upserts the asc.*
// CostRegistry items, the inp.* programme inputs, the LineTemplate rows, and
// (defensively) the BudgetDomainConfig row — for Bangalore + Chennai.
//
// Mirrors scripts/seed-water-sanitation-domains.ts. Create-only on collisions;
// never overwrites admin edits. Safe to re-run.
//
// Run: node --env-file=.env.local ./node_modules/.bin/tsx scripts/seed-afterschool-templates.ts

import { config } from "dotenv";
config({ path: ".env.local" });
import { PrismaClient } from "../app/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { DEFAULT_COSTS } from "../lib/budget-costs";
import { getTemplatesForCity } from "../lib/line-template-seeds";

const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL! }) });

const DOMAIN = "AfterSchoolCentre";
const CITIES = ["Bangalore", "Chennai"];

const NEW_PROG_INPUTS = [
  { itemKey: "inp.nAfterSchoolCentres",   unit: "count",   unitCost: 1,   notes: "No. of after-school centres",                displayGroup: "facilities" },
  { itemKey: "inp.targetChildrenPerDay",  unit: "count",   unitCost: 300, notes: "Children per day (drives food-cost line)",   displayGroup: "coverage" },
  { itemKey: "inp.ascCentreRentPerMonth", unit: "₹/month", unitCost: 0,   notes: "After-school centre site rent (usually 0)",  displayGroup: "facilities" },
];

const DOMAIN_CFG = {
  key: "AfterSchoolCentre",
  label: "After-School Centre",
  description: "One plan per school (Moulana Azad Model Schools, Directorate of Minorities pilot).",
  position: 8,
  beneficiaryLabel: "Children per day",
  beneficiaryVar: "targetChildrenPerDay",
  beneficiaryMult: 1,
  isActive: true,
};

async function main() {
  const regItems = DEFAULT_COSTS.filter((c) => c.domain === DOMAIN);
  for (const city of CITIES) {
    let reg = 0, pin = 0, tpl = 0, dom = 0;
    // 1. CostRegistry — asc.* items
    for (const c of regItems) {
      await prisma.costRegistry.upsert({
        where: { city_itemKey: { city, itemKey: c.itemKey } },
        create: { city, domain: c.domain ?? undefined, itemKey: c.itemKey, unitCost: c.unitCost, unit: c.unit, effectiveYear: 2025, notes: c.notes },
        update: {},
      });
      reg++;
    }
    // 2. CostRegistry — inp.* programme inputs
    for (const d of NEW_PROG_INPUTS) {
      await prisma.costRegistry.upsert({
        where: { city_itemKey: { city, itemKey: d.itemKey } },
        create: { city, domain: null, effectiveYear: 2025, ...d },
        update: { displayGroup: d.displayGroup, notes: d.notes },
      });
      pin++;
    }
    // 3. LineTemplate — position = index in the full per-city template list.
    //    Existing rows: keep hand-edits, but always update applyY2/applyY3 so
    //    capex isn't re-charged in Y2+ (one-time-capex flag; new field, safe
    //    to overwrite).
    const all = getTemplatesForCity(city);
    for (let i = 0; i < all.length; i++) {
      const t = all[i];
      if (t.domain !== DOMAIN) continue;
      const applyY2 = (t as { applyY2?: boolean }).applyY2 ?? true;
      const applyY3 = (t as { applyY3?: boolean }).applyY3 ?? true;
      await prisma.lineTemplate.upsert({
        where: { city_templateKey: { city, templateKey: t.templateKey } },
        update: { applyY2, applyY3 },
        create: {
          city, templateKey: t.templateKey, position: i,
          section: t.section as never, description: t.description, costCategory: t.costCategory as never,
          unitType: t.unitType, notes: t.notes ?? null, salaryHint: t.salaryHint ?? null,
          isAutoGenerated: t.isAutoGenerated ?? true, domain: (t.domain as never) ?? null,
          inputVar: t.inputVar ?? "fixed_1", inputMonthly: t.inputMonthly ?? false,
          supervisorRatioKey: t.supervisorRatioKey ?? null, isSalaryStub: t.isSalaryStub ?? false,
          userInputCost: t.userInputCost ?? null, costKey: t.costKey ?? null, costKey2: t.costKey2 ?? null,
          costKey3: t.costKey3 ?? null, costMonthly: t.costMonthly ?? false, workerRatioKey: t.workerRatioKey ?? null,
          bufferKey: t.bufferKey ?? null, costPctOf: t.costPctOf ?? null, costPct: t.costPct ?? null,
          y1UnitsZero: t.y1UnitsZero ?? false, applyY2, applyY3,
        },
      });
      tpl++;
    }
    // 4. BudgetDomainConfig (defensive — the school-plan seed already created it)
    await prisma.budgetDomainConfig.upsert({
      where: { city_key: { city, key: DOMAIN_CFG.key } },
      create: { city, ...DOMAIN_CFG },
      update: {},
    });
    dom++;

    console.log(`${city}: registry=${reg} progInputs=${pin} templates=${tpl} domains=${dom}`);
  }
  await prisma.$disconnect();
}
main().catch((e) => { console.error(e); process.exit(1); });
